= Checkstyle
:page-aliases: Plugin_Checkstyle.adoc

Performs quality checks on Java source files using https://checkstyle.org[Checkstyle] and generates reports from these checks.

Transformations to be applied on the Checkstyle report are detected automatically.
[source,scala]
----
/*
Directory structure:

  checkstyle
    ├─ html
    │   ├─ xslt0.xml
    │   └─ xslt1.xml
    ├─ pdf
    │   ├─ xslt1.xml
    │   └─ xslt2.xml
    └─ config.xml

Transformations:

 - checkstyle/html/xslt0.xml -> xslt0.html
 - checkstyle/html/xslt1.xml -> xslt1.html
 - checkstyle/pdf/xslt1.xml  -> xslt1.pdf
 - checkstyle/pdf/xslt2.xml  -> xslt2.pdf
 */
----

== Usage

To use this plugin in a Java/Scala module,

1. Extend `mill.contrib.checkstyle.CheckstyleModule`.
2. Define a https://checkstyle.org/config.html[configuration] file `checkstyle` `/` `config.xml`.
3. Optionally, define transformations under `checkstyle` directory.
4. Run the `checkstyle` task to generate report(s).

To use this plugin with a configuration shared across modules, adapt the following example.

[source,scala]
----
import mill._
import mill.contrib.checkstyle.CheckstyleModule
import mill.scalalib._

object foo extends Module {

  object bar extends MyModule
  object baz extends Module {
    object fizz extends MyModule
    object buzz extends MyModule
  }

  trait MyModule extends JavaModule with CheckstyleModule {

    def checkstyleDir = {
      // TODO how to detect project root directory from any nested module?
      val root: os.Path = ???
      api.PathRef(root / "checkstyle")
    }
  }
}
----

== Limitations
- Transformations are not supported for `plain` and `sarif` formats.
- Version `6.3` or above is required for `plain` and `xml` formats.
- Using `checkstyleOptions` with legacy versions might cause failures.
