# action.yml
inputs:
  java-version:
    required: true
    type: string

  timeout-minutes:
    default: 60
    type: number

  os:
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin

    - uses: actions/checkout@v4

    # Need to fix cached artifact file permissions because github actions screws it up
    # https://github.com/actions/upload-artifact/issues/38
    - name: chmod executable
      run: "chmod -R +x ."
      shell: bash

    - uses: coursier/cache-action@v6
