= Support for New Languages

include::partial$gtag-config.adoc[]

This section walks through the process of adding support for a new programming
language to Mill. We will be adding a small `trait TypeScriptModule` with the
ability to resolve dependencies, typecheck local code, and optimize a final
bundle.

The TypeScript integration here is not intended for production usage, but is
instead meant for illustration purposes of the techniques typically used in
implementing language toolchains.

== Basic TypeScript Pipeline

include::partial$example/extending/newlang/1-hello-typescript.adoc[]

== Re-usable TypeScriptModule

include::partial$example/extending/newlang/2-typescript-modules.adoc[]

== TypeScriptModule `moduleDeps`

include::partial$example/extending/newlang/3-module-deps.adoc[]

== NPM dependencies and bundling

include::partial$example/extending/newlang/4-npm-deps-bundle.adoc[]




As mentioned earlier, the `TypeScriptModule` examples on this page are meant for
demo purposes: to show what it looks like to add support in Mill for a new
programming language toolchain. It would take significantly more work to flesh out
the featureset and performance of `TypeScriptModule` to be usable in a real world
build. But this should be enough to get you started working with Mill to add support
to any language you need: whether it's TypeScript or some other language, most programming
language toolchains have similar concepts of `compile`, `run`, `bundle`, etc.


== Python Support

This section demonstrates how to integrate `Python` support into `Mill`.
We will define a simple `PythonModule` trait that can resolve dependencies,
perform type checking on local code, and optimize the final bundle.
 
`Note`: This integration is for `educational purposes only`, showcasing common technique
used in building language toolchains, and is not intended for production use.

include::partial$example/extending/newlang/5-hello-python.adoc[]

include::partial$example/extending/newlang/6-python-modules.adoc[]

include::partial$example/extending/newlang/7-python-module-deps.adoc[]

include::partial$example/extending/newlang/8-python-libs-bundle.adoc[]



As mentioned, The `PythonModule` examples here demonstrate 
how to add support for a new language toolchain in Mill.
A production-ready version would require more work to enhance features and performance.