extends: [mill.javalib.MavenModule]
mvnDeps:
- "net.sourceforge.argparse4j:argparse4j:0.9.0"
- "org.thymeleaf:thymeleaf:3.1.1.RELEASE"

object test:
  extends: [build.MavenTests, mill.javalib.TestModule.Junit4]
  mvnDeps:
  - "com.google.guava:guava:33.3.0-jre"

object integration:
  extends: [build.MavenTests, mill.javalib.TestModule.Junit4]
  mvnDeps:
  - "com.google.guava:guava:33.3.0-jre"