= Auto-Migrating Existing Projects
:icons: font



The Mill `init` command can be used to convert a Maven, Gradle, or SBT build to Mill.
This has xref:#limitations[limitations] and is not intended to reliably migrate 100% of
existing builds out there in the wild, but is instead meant to provide the basic
scaffolding of a Mill build for you to further refine and update manually.

Each Maven module with a `pom.xml`, Gradle module with a `.gradle` file, or SBT module
is converted to a Mill `build.mill`/`package.mill` file containing a top-level `MavenModule`
or `SbtModule`. A nested `test` module is defined, if `src/test` exists, and is configured
with a supported xref:javalib/testing.adoc[test framework], if found.

Again, note that `mill init` importing Maven builds is best-effort.
This means that while small projects can be expected to complete without issue:

**Maven**

include::partial$example/migrating/javalib/1-maven-complete.adoc[]

**Gradle**

include::partial$example/migrating/javalib/4-gradle-complete.adoc[]

**SBT**

include::partial$example/migrating/scalalib/1-sbt-complete.adoc[]

Larger projects often require some manual tweaking in order to work:

**Maven**

include::partial$example/migrating/javalib/2-maven-incomplete.adoc[]

**Gradle**

include::partial$example/migrating/javalib/5-gradle-incomplete.adoc[]

**SBT**

include::partial$example/migrating/scalalib/2-sbt-incomplete.adoc[]

Nevertheless, even for larger builds `mill init` automates most of the tedious
busy-work of writing `build.mill`/`package.mill` files, and makes it much quicker
to get a working Mill build for any existing Maven project. For example,
the `iluwatar/java-design-patterns` repo has 363 subprojects
(including test projects) and `./mill init` is able to get it imported,
compiling, and passing all tests in Mill:

include::partial$example/migrating/javalib/3-maven-complete-large.adoc[]


== Capabilities

The conversion

* handles deeply nested modules
* captures publish settings
* configures dependencies for configurations:
** no configuration
** Compile
** Test
** Runtime
** Provided
** Optional
* configures testing frameworks:
** Java:
*** JUnit 4
*** JUnit 5
*** TestNG
** Scala:
*** ScalaTest
*** Specs2
*** µTest
*** MUnit
*** Weaver
*** ZIOTest
*** ScalaCheck

* configures multiple, compile and test, resource directories

=== Command line arguments

The conversion and its output (the generated Mill build files) can be customized using

* `--base-module` (`-b`): name of generated base module trait defining shared settings
+
[source,sh]
----
./mill init --base-module MyModule
----

* `--jvm-id` (`-j`): disttribution and version of xref:fundamentals/configuring-jvm-versions.adoc[custom JVM] to configure in `--base-module`
+
[source,sh]
----
./mill init --base-module MyModule --jvm-id 17
./mill init --base-module MyModule --jvm-id temurin:17
./mill init --base-module MyModule --jvm-id temurin:17.0.1
----

* `--test-module` (`-t`): name of generated nested test module (defaults to `test`)
+
[source,sh]
----
./mill init --test-module test
----

* `--deps-object` (`-d`): name of generated companion object defining dependency constants
+
[source,sh]
----
./mill init --deps-object Deps
----

* `--merge` (`-m`): merge build files generated for a multi-module build
+
[source,sh]
----
./mill init --merge
----

* `--publish-properties` (`-p`): capture Maven publish properties
+
[source,sh]
----
./mill init --publish-properties
----

* `--cache-repository`: use cache for Maven repository system
+
[source,sh]
----
./mill init --cache-repository
----

* `--process-plugins`: process Maven plugin executions and configurations
+
[source,sh]
----
./mill init --process-plugins
----

TIP: You can run `mill init` multiple times. It is recommended to run it first without any options.

=== Verified projects

The conversion has been tested with the following projects:

* https://github.com/fusesource/jansi/archive/refs/tags/jansi-2.4.1.zip[jansi]
[source,sh]
----
./mill init --base-module JansiModule --deps-object Deps --cache-repository --process-plugins
----

* https://github.com/davidmoten/geo/archive/refs/tags/0.8.1.zip[geo] (multi-module build)
[source,sh]
----
./mill init --base-module GeoModule --deps-object Deps --merge --cache-repository --process-plugins
----

Post `init`, the following tasks were executed successfully:

* `compile`
* `test`
* `publishLocal`

[#limitations]
== Limitations

The conversion does not support

* build extensions
* build profiles
* non-Java sources

Maven plugin support is limited to

* https://maven.apache.org/plugins/maven-compiler-plugin/[maven-compiler-plugin]

[TIP]
====
These limitations can be overcome by:

* configuring equivalent Mill xref:extending/contrib-plugins.adoc[contrib]
  or xref:extending/thirdparty-plugins.adoc[third party] plugins
* defining custom xref:extending/writing-plugins.adoc[plugins]
* defining custom xref:fundamentals/tasks.adoc[tasks]
* defining custom xref:fundamentals/cross-builds.adoc[cross modules]
====

== FAQ

=== How to fix compilation errors in generated build files?

This could happen if a module and task name collision occurs. Either rename the module or enclose the name in backticks.

=== How to fix JPMS `module not found` compilation errors?

Add https://github.com/tfesenko/Java-Modules-JPMS-CheatSheet#how-to-export-or-open-a-package[options]
for Java modules to `javacOptions`.

=== How to fix test compilation errors?

* The test framework configured may be for an unsupported version; try upgrading the
  corresponding dependencies.
* Mill does not add `compileMvnDeps` dependencies to the transitive dependencies of the nested
test module; specify the dependencies again, in `mvnDeps` or `runMvnDeps`.

=== `java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI`

This error:
`java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release`,
`java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI`,
and `java.lang.RuntimeException: java.lang.reflect.InvocationTargetException`
thrown by the `sbt` command invoked by `mill init`

Update the project's `sbt` version to the latest or our tested version v1.10.10,
and check whether you have the appropriate Java version,
and try again.