= Importing Gradle Projects
:page-aliases: Migrating_A_Gradle_Build_to_Mill.adoc
:icons: font



The Mill `init` command can be used to convert a Gradle build to Mill. This has
xref:#limitations[limitations] and is not intended to reliably migrate 100% of
Gradle builds out there in the wild, but is instead meant to provide the basic
scaffolding of a Mill build for you to further refine and update manually.

Each Gradle project in a build tree is converted to a Mill module.
A nested `test` module is defined, if `src/test` exists, and is configured with a supported xref:javalib/testing.adoc[test framework], if found.

Again, note that `mill init` imports a Gradle build on a best-effort basis.
This means that while simple projects can be expected to complete without issue:

include::partial$example/migrating/javalib/3-gradle-complete.adoc[]

Projects with a complex build often require some manual tweaking in order to work:

include::partial$example/migrating/javalib/4-gradle-incomplete.adoc[]

== Capabilities

The conversion

* handles deeply nested modules
* captures publish settings
* configures dependencies for https://docs.gradle.org/current/userguide/dependency_configurations.html#sub:what-are-dependency-configurations[configurations]
** implementation / api
** compileOnly / compileOnlyApi
** runtimeOnly
** testImplementation
** testCompileOnly
* configures testing frameworks
** JUnit 4
** JUnit 5
** TestNG

[#arguments]
=== Command line arguments

The conversion and its output (the generated Mill build files) can be customized using

* `--base-module` (`-b`): name of generated base module trait defining shared settings
+
[source,sh]
----
./mill init --base-module MyModule
----

* `--base-project` (`-g`): name of Gradle project to extract settings for `--base-module`
+
[source,sh]
----
./mill init --base-module MyModule --base-project lib
----
NOTE: If not specified, a project will be selected arbitrarily.

* `--jvm-id` (`-j`): distribution and version of xref:fundamentals/configuring-jvm-versions.adoc[custom JVM] to configure in `--base-module`
+
[source,sh]
----
./mill init --base-module MyModule --jvm-id 17
./mill init --base-module MyModule --jvm-id temurin:17
./mill init --base-module MyModule --jvm-id temurin:17.0.1
----

* `--test-module` (`-t`): name of generated nested test module (defaults to `test`)
+
[source,sh]
----
./mill init --test-module test
----

* `--deps-object` (`-d`): name of generated companion object defining dependency constants
+
[source,sh]
----
./mill init --deps-object Deps
----

* `--merge` (`-m`): merge build files generated for a multi-module build
+
[source,sh]
----
./mill init --merge
----

* `--publish-properties` (`-p`): capture Maven publish properties
+
[source,sh]
----
./mill init --publish-properties
----

TIP: You can run `mill init` multiple times. It is recommended to run it first without any options.

[#limitations]
== Limitations

The conversion does not support

* custom dependency configurations
* custom tasks
* non-Java sources

Gradle plugin support is limited to

* https://docs.gradle.org/current/userguide/java_plugin.html[java]
* https://docs.gradle.org/current/userguide/publishing_maven.html[maven-publish]

[TIP]
====
These limitations can be overcome by:

* configuring equivalent Mill xref:extending/contrib-plugins.adoc[contrib]
or xref:extending/thirdparty-plugins.adoc[third party] plugins
* defining custom xref:extending/writing-plugins.adoc[plugins]
* defining custom xref:fundamentals/tasks.adoc[tasks]
* defining custom xref:fundamentals/cross-builds.adoc[cross modules]
====

== FAQ

How to fix `java.lang.UnsupportedClassVersionError` error thrown by `mill init`?

Select a https://docs.gradle.org/current/userguide/compatibility.html#java_runtime[Java Runtime] compatible with the version of Gradle used and pass it using the `--jvm-id` xref:arguments[argument].

How to fix test compilation errors?

* The test framework configured may be for an unsupported version; try upgrading the
corresponding dependencies.
* Mill does not add `compileMvnDeps` dependencies to the transitive dependencies of the nested
test module; specify the dependencies again, in `mvnDeps` or `runMvnDeps`.
