= Importing `sbt` Projects
:page-aliases: Migrating_An_sbt_Build_to_Mill.adoc
:icons: font



The Mill `init` command can be used to convert an `sbt` build to Mill. This has
xref:#limitations[limitations] and is not intended to reliably migrate 100% of
`sbt` builds out there in the wild, but is instead meant to provide the basic
scaffolding of a Mill build for you to further refine and update manually.

Each `sbt` project in a build tree is converted to a Mill module.
A nested `test` module is defined, if `src/test` exists, and is configured with a supported xref:scalalib/testing.adoc[test framework], if found.

Again, note that `mill init` imports an `sbt` build on a best-effort basis.
This means that while simple projects can be expected to complete without issue:

include::partial$example/migrating/scalalib/1-sbt-complete.adoc[]

Projects with a complex build often require some manual tweaking in order to work:

include::partial$example/migrating/scalalib/2-sbt-incomplete.adoc[]

== Capabilities

The conversion

* handles deeply nested modules
* captures publish settings
* configures dependencies for configurations:
** no configuration
** Compile
** Test
** Runtime
** Provided
** Optional
* configures testing frameworks:
** Java:
*** JUnit 4
*** JUnit 5
*** TestNG
** Scala:
*** ScalaTest
*** Specs2
*** µTest
*** MUnit
*** Weaver
*** ZIOTest
*** ScalaCheck

[#arguments]
=== Command line arguments

The conversion and its output (the generated Mill build files) can be customized using

* `--base-module` (`-b`): name of generated base module trait defining shared settings
+
[source,sh]
----
./mill init --base-module MyModule
----

* `--test-module` (`-t`): name of generated nested test module (defaults to `test`)
+
[source,sh]
----
./mill init --test-module test
----

* `--deps-object` (`-d`): name of generated companion object defining dependency constants
+
[source,sh]
----
./mill init --deps-object Deps
----

* `--merge` (`-m`): merge build files generated for a multi-module build
+
[source,sh]
----
./mill init --merge
----

TIP: You can run `mill init` multiple times. It is recommended to run it first without any options.

[#limitations]
== Limitations

The conversion does not support:

* custom dependency configurations
* custom settings including custom tasks
* sources other than Scala on JVM and Java, such as Scala.js and Scala Native
* cross builds

`sbt` plugin support is limited to:

* https://www.scala-sbt.org/1.x/api/sbt/plugins/JvmPlugin$.html[`JvmPlugin`]

[TIP]
====
These limitations can be overcome by:

* configuring equivalent Mill xref:extending/contrib-plugins.adoc[contrib]
or xref:extending/thirdparty-plugins.adoc[third party] plugins
* defining custom xref:extending/writing-plugins.adoc[plugins]
* defining custom xref:fundamentals/tasks.adoc[tasks]
* defining custom xref:fundamentals/cross-builds.adoc[cross modules]
====

== FAQ

How to fix errors such as
`java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release`,
`java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI`,
and `java.lang.RuntimeException: java.lang.reflect.InvocationTargetException`
thrown by the `sbt` command invoked by `mill init`?

Update the project's `sbt` version to the latest or our tested version v1.10.10,
and check whether you have the appropriate Java version,
and try again.

How to fix test compilation errors?

* The test framework configured may be for an unsupported version; try upgrading the
corresponding dependencies.
* Mill does not add `compileMvnDeps` dependencies to the transitive dependencies of the nested
test module; specify the dependencies again, in `mvnDeps` or `runMvnDeps`.
