= Contributing to Mill
:link-github: https://github.com/com-lihaoyi/mill


Thank you for considering contributing to Mill.

We have essential contributor information in the xref:readme.adoc[Project README].

Here are some direct links:

* xref:developer.adoc#intellij-setup[IntelliJ Setup] - IntelliJ IDEA works great for Mill development; other IDEs may work as well
* xref:developer.adoc#project-layout[Project Layout] - The source code repository structure from a high level view
* xref:developer.adoc#manual-automated-testing[Manual and Automated Testing] - How we test Mill
* xref:developer.adoc#project-maintenance[Project Maintenance] - Details about authoring pull request and commit messages
* https://mill-build.org/mill/Intro_to_Mill.html[Mill Documentation] - Documentation for users and developers
* {link-github}/discussions[Discussion Forum on GitHub] - A place to ask question and discuss all kind of questions around Mill
* {link-github}/issues[Issue Tracker on GitHub] - Our issue tracker for bugs and features
* {link-github}/pulls[Pull Requests on GitHub] - All new features and bug fixes find their way into Mill via a pull request. You can also sketch new ideas by creating a draft pull requests.


To build docs locally, `mill docs.localPages`. The last line of the command tells you where to browse the generated pages. From there you can follow the breadcrumbs.
