= image:docs/logo.svg[Mill Logo] Mill
:idprefix:
:idseparator: -
:link-github: https://github.com/com-lihaoyi/mill
:link-current-doc-site: https://mill-build.org
:link-mill-moduledefs: https://github.com/com-lihaoyi/mill-moduledefs
:example-scala-version: 3.3.4
:toc:
:toc-placement: preamble
ifndef::env-github[]
:icons: font
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

https://github.com/com-lihaoyi/mill/blob/main/changelog.adoc[image:https://index.scala-lang.org/com-lihaoyi/mill/mill-main/latest.svg[Mill]]
https://central.sonatype.com/artifact/com.lihaoyi/mill-dist[image:https://img.shields.io/maven-central/v/com.lihaoyi/mill-dist?label=latest-unstable[Maven Central Version]]


Mill is a fast, scalable, multi-language build tool that supports Java, Scala,
Kotlin, and Python:

* Mill can build the same Java codebase 4-10x faster than Maven,
or 2-4x faster than Gradle

* Mill comes builtin with all the tools needed to develop and publish your project without
needing plugins

* Mill's typed config language and immutable task graph
helps keep builds clean and understandable

* Mill scales well from small projects to
large multi-language monorepos with hundreds of modules

If you want to use Mill in your own projects, check out our documentation:

* {link-current-doc-site}[Documentation]

Here is some quick example, so that you can imagine how it looks:

[source,scala,subs="verbatim,attributes"]
----
package build
import mill._, javalib._

object foo extends JavaModule {
  def ivyDeps = Agg(
    mvn"net.sourceforge.argparse4j:argparse4j:0.9.0",
    mvn"org.thymeleaf:thymeleaf:3.1.1.RELEASE"
  )

  object test extends JavaTests with TestModule.Junit4 {
    def ivyDeps = super.ivyDeps() ++ Agg(
      mvn"com.google.guava:guava:33.3.0-jre"
    )
  }
}
----

[source,bash]
----

> ./mill foo.compile # compile sources into classfiles
...
compiling 1 Java source to...

> ./mill foo.run --text hello
<h1>hello</h1>

> ./mill foo.test
...
Test foo.FooTest.testEscaping finished, ...
Test foo.FooTest.testSimple finished, ...
Test run foo.FooTest finished: 0 failed, 0 ignored, 2 total, ...

----

* https://github.com/com-lihaoyi/mill/blob/main/developer.adoc[Developer Documentation]
* https://github.com/com-lihaoyi/mill/blob/main/changelog.adoc[Changelog]


