(function(){
'use strict';var aa;function h(a){this.Z=a}h.prototype.toString=function(){return String.fromCharCode(this.Z)};
function ba(a){switch(typeof a){case "string":return"java.lang.String";case "number":return ca(a)?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":da(a)?"java.lang.Float":"java.lang.Double";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return a instanceof k?"java.lang.Long":a instanceof h?"java.lang.Character":a&&a.$classData?a.$classData.name:null.Ja()}}
function ea(a){switch(typeof a){case "string":return l(a);case "number":return fa(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.n():a instanceof k?a.v^a.u:a instanceof h?null===a?0:a.Z:m.prototype.n.call(a)}}var n=new DataView(new ArrayBuffer(8)),ha=0,ia=new WeakMap;
function ja(a){switch(typeof a){case "string":return l(a);case "number":return fa(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:l(a);default:if(null===a)return 0;b=ia.get(a);void 0===b&&(ha=b=ha+1|0,ia.set(a,b));return b}}function ca(a){return"number"===typeof a&&(a|0)===a&&1/a!==1/-0}
function da(a){return"number"===typeof a&&(a!==a||Math.fround(a)===a)}function m(){}m.prototype.constructor=m;function p(){}p.prototype=m.prototype;m.prototype.n=function(){return ja(this)};m.prototype.h=function(){var a=this.n();return ba(this)+"@"+(a>>>0).toString(16)};m.prototype.toString=function(){return this.h()};function q(a){if("number"===typeof a){this.b=Array(a);for(var b=0;b<a;b++)this.b[b]=null}else this.b=a}q.prototype=new p;q.prototype.constructor=q;function ka(){}ka.prototype=q.prototype;
function la(a){if("number"===typeof a){this.b=Array(a);for(var b=0;b<a;b++)this.b[b]=!1}else this.b=a}la.prototype=new p;la.prototype.constructor=la;function ma(a){this.b="number"===typeof a?new Uint16Array(a):a}ma.prototype=new p;ma.prototype.constructor=ma;function na(a){this.b="number"===typeof a?new Int8Array(a):a}na.prototype=new p;na.prototype.constructor=na;function oa(a){this.b="number"===typeof a?new Int16Array(a):a}oa.prototype=new p;oa.prototype.constructor=oa;
function pa(a){this.b="number"===typeof a?new Int32Array(a):a}pa.prototype=new p;pa.prototype.constructor=pa;function qa(a){if("number"===typeof a){this.b=Array(a);for(var b=0;b<a;b++)this.b[b]=aa}else this.b=a}qa.prototype=new p;qa.prototype.constructor=qa;function ra(a){this.b="number"===typeof a?new Float32Array(a):a}ra.prototype=new p;ra.prototype.constructor=ra;function sa(a){this.b="number"===typeof a?new Float64Array(a):a}sa.prototype=new p;sa.prototype.constructor=sa;
function r(){this.J=void 0;this.x=this.i=null;this.y=0;this.la=null;this.m="";this.q=this.w=void 0;this.name="";this.K=!1;this.z=void 0}function t(a,b,c,d){var e=new r;e.i={};e.la=a;e.m=b;e.q=f=>f===e;e.name=c;e.K=!0;e.z=()=>!1;void 0!==d&&(e.w=ta(e,d));return e}function u(a,b,c,d){var e=new r,f=Object.getOwnPropertyNames(c)[0];e.i=c;e.m="L"+b+";";e.q=g=>!!g.i[f];e.name=b;e.z=d||(g=>!!(g&&g.$classData&&g.$classData.i[f]));"number"!==typeof a&&(a.prototype.$classData=e);return e}
function ta(a,b,c){var d=new r;b.prototype.$classData=d;var e="["+a.m;d.J=b;d.i={L:1,a:1};d.x=a;d.y=1;d.m=e;d.name=e;d.q=c||(f=>d===f);d.z=f=>f instanceof b;return d}
function ua(){function a(g){if("number"===typeof g){this.b=Array(g);for(var H=0;H<g;H++)this.b[H]=null}else this.b=g}var b=va,c=new r;a.prototype=new ka;a.prototype.constructor=a;a.prototype.$classData=c;var d=b.x||b,e=b.y+1;b="["+b.m;c.J=a;c.i={L:1,a:1};c.x=d;c.y=e;c.m=b;c.name=b;var f=g=>{var H=g.y;return H===e?d.q(g.x):H>e&&d===v};c.q=f;c.z=g=>{g=g&&g.$classData;return!!g&&(g===c||f(g))};return c}var v=new r;v.i={};v.m="Ljava.lang.Object;";v.q=a=>!a.K;v.name="java.lang.Object";v.z=a=>null!==a;
v.w=ta(v,q,a=>{var b=a.y;return 1===b?!a.x.K:1<b});m.prototype.$classData=v;t(void 0,"V","void",void 0);t(!1,"Z","boolean",la);t(0,"C","char",ma);t(0,"B","byte",na);t(0,"S","short",oa);t(0,"I","int",pa);var wa=t(null,"J","long",qa);t(0,"F","float",ra);t(0,"D","double",sa);function w(){window.document.documentElement}w.prototype=new p;w.prototype.constructor=w;u(w,"dotty.tools.scaladoc.ContentContributors",{Ea:1});u(0,"java.lang.Void",{Xa:1},a=>void 0===a);function k(a,b){this.v=a;this.u=b}
k.prototype=new p;k.prototype.constructor=k;k.prototype.n=function(){return this.v^this.u};k.prototype.h=function(){xa();var a=this.v;var b=this.u;if(b===a>>31)b=""+a;else if(0===(-2097152&(b^b>>10)))b=""+(4294967296*b+(a>>>0));else{var c=b>>31,d=a^c;a=d-c|0;c=+Math.floor(1E-9*(4294967296*(((b^c)+((d&~a)>>>31|0)|0)>>>0)+(a>>>0)));a=a-Math.imul(1E9,c|0)|0;0>a?(--c,a=1E9+a|0):1E9<=a&&(c+=1,a=-1E9+a|0);a=""+a;c=""+c+"000000000".substring(a.length)+a;b=0>b?"-"+c:c}return b};
u(k,"org.scalajs.linker.runtime.RuntimeLong",{Ga:1});function x(){this.C=0}x.prototype=new p;x.prototype.constructor=x;function ya(a,b){if(-0x7fffffffffffffff>b)return a.C=-2147483648,0;if(0x7fffffffffffffff<=b)return a.C=2147483647,-1;var c=b|0,d=b/4294967296|0;a.C=0>b&&0!==c?-1+d|0:d;return c}u(x,"org.scalajs.linker.runtime.RuntimeLong$",{Ha:1});var za;function xa(){za||(za=new x);return za}
function Aa(a,b,c,d,e){var f=b.p;0!==c.length&&(f.c=""+f.c+c);a=a.j();if(a.e())for(c=a.d(),f.c=""+f.c+c;a.e();)f.c=""+f.c+d,c=a.d(),f.c=""+f.c+c;0!==e.length&&(f.c=""+f.c+e);return b}function y(){}y.prototype=new p;y.prototype.constructor=y;u(y,"scala.collection.mutable.MutationTracker$",{Gb:1});var Ba;function z(){}z.prototype=new p;z.prototype.constructor=z;
function Ca(a){var b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)return b;var c=xa();b=ya(c,a);c=c.C;if(4294967296*c+(b>>>0)===a)return b^c;b=a|0;if(b===a&&-Infinity!==1/a)return b;if(a!==a)return 2146959360;n.setFloat64(0,a,!0);return(n.getInt32(0,!0)|0)^(n.getInt32(4,!0)|0)}function A(a,b){return null===b?0:"number"===typeof b?Ca(+b):b instanceof k?(a=null===b?aa:b,b=new k(a.v,a.u),a=b.v,b=b.u,b===a>>31?a:a^b):ea(b)}u(z,"scala.runtime.Statics$",{Mb:1});var Da;
function B(){Da||(Da=new z);return Da}function Ea(){}Ea.prototype=new p;Ea.prototype.constructor=Ea;function Fa(){}Fa.prototype=Ea.prototype;function C(a,b){a=Ga(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function Ga(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}function D(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}
function E(a,b){a.M=b;"[object Error]"!==Object.prototype.toString.call(a)&&(void 0===Error.captureStackTrace||Object.isSealed(a)?Error():Error.captureStackTrace(a))}class Ha extends Error{constructor(){super();this.M=null}h(){var a=ba(this),b=this.M;return null===b?a:a+": "+b}n(){return m.prototype.n.call(this)}get message(){var a=this.M;return null===a?"":a}get name(){return ba(this)}toString(){return this.h()}}function F(){}F.prototype=new p;F.prototype.constructor=F;function Ia(){}
Ia.prototype=F.prototype;F.prototype.h=function(){return"\x3cfunction0\x3e"};function G(){this.da=this.H=0;Ja=this;this.H=l("Seq");this.da=l("Map");l("Set");var a=I(),b=this.da,c=0,d=0,e=0,f=1;for(a=a.j();a.e();){var g=a.d();g=A(B(),g);c=c+g|0;d^=g;f=Math.imul(f,1|g);e=1+e|0}b=C(b,c);b=C(b,d);b=Ga(b,f);D(b^e)}G.prototype=new Fa;G.prototype.constructor=G;u(G,"scala.util.hashing.MurmurHash3$",{db:1,cb:1});var Ja;function J(){this.X=null;Ka=this;var a=+Date.now();ya(xa(),a);this.X=new K;new w}
J.prototype=new p;J.prototype.constructor=J;u(J,"dotty.tools.scaladoc.Main$",{Fa:1,ab:1,$a:1});var Ka;class La extends Ha{}function L(){this.I=null;Ma=this;this.I=new M}L.prototype=new p;L.prototype.constructor=L;u(L,"scala.collection.Iterator$",{kb:1,jb:1,a:1});var Ma;function Na(){Ma||(Ma=new L);return Ma}function N(a){this.V=a}N.prototype=new Ia;N.prototype.constructor=N;u(N,"scala.runtime.AbstractFunction0.$$Lambda$a02b774b97db8234e08c6a02dd06557c99779855",{Lb:1,Kb:1,Da:1});
u(0,"java.lang.Boolean",{Ma:1,a:1,k:1,l:1},a=>"boolean"===typeof a);u(0,"java.lang.Character",{Oa:1,a:1,k:1,l:1},a=>a instanceof h);class O extends La{}function P(){this.c=""}P.prototype=new p;P.prototype.constructor=P;P.prototype.h=function(){return this.c};P.prototype.g=function(){return this.c.length};u(P,"java.lang.StringBuilder",{Va:1,aa:1,Ka:1,a:1});function Q(){}Q.prototype=new p;Q.prototype.constructor=Q;function Oa(){}Oa.prototype=Q.prototype;Q.prototype.j=function(){return this};
Q.prototype.h=function(){return"\x3citerator\x3e"};Q.prototype.Y=function(a,b,c,d){return Aa(this,a,b,c,d)};Q.prototype.o=function(){return-1};class Pa extends O{constructor(a){super();E(this,a)}}u(Pa,"java.lang.ArithmeticException",{La:1,E:1,D:1,F:1,a:1});u(0,"java.lang.Byte",{Na:1,A:1,a:1,k:1,l:1},a=>"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0);class Qa extends O{constructor(a){super();E(this,a)}}u(Qa,"java.lang.IndexOutOfBoundsException",{Ra:1,E:1,D:1,F:1,a:1});
u(0,"java.lang.Short",{Ua:1,A:1,a:1,k:1,l:1},a=>"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0);class Ra extends O{constructor(a){super();E(this,a)}}u(Ra,"java.lang.UnsupportedOperationException",{Wa:1,E:1,D:1,F:1,a:1});class Sa extends O{constructor(a){super();E(this,a)}}u(Sa,"java.util.ConcurrentModificationException",{Ya:1,E:1,D:1,F:1,a:1});class Ta extends O{constructor(a){super();E(this,a)}}u(Ta,"java.util.NoSuchElementException",{Za:1,E:1,D:1,F:1,a:1});function M(){}M.prototype=new Oa;
M.prototype.constructor=M;M.prototype.e=function(){return!1};M.prototype.o=function(){return 0};M.prototype.d=function(){throw new Ta("next on empty iterator");};u(M,"scala.collection.Iterator$$anon$19",{lb:1,ea:1,ga:1,s:1,t:1});function Ua(a,b){if(0>b)throw new Qa(""+b);a:for(var c=b;;){if(0>=c||a===I())break a;c=-1+c|0;Va();a=void 0}if(a===I())throw new Qa(""+b);Wa()}function R(a,b){this.ja=0;this.ka=a;this.za=b;this.ja=(0,b.V)()|0}R.prototype=new Oa;R.prototype.constructor=R;
R.prototype.e=function(){Ba||(Ba=new y);if(((0,this.za.V)()|0)!==this.ja)throw new Sa("mutation occurred during iteration");return this.ka.e()};R.prototype.d=function(){return this.ka.d()};u(R,"scala.collection.mutable.MutationTracker$CheckedIterator",{Hb:1,ea:1,ga:1,s:1,t:1});function fa(a){var b=a|0;if(b===a&&-Infinity!==1/a)return b;if(a!==a)return 2146959360;n.setFloat64(0,a,!0);return(n.getInt32(0,!0)|0)^(n.getInt32(4,!0)|0)}u(0,"java.lang.Double",{Pa:1,A:1,a:1,k:1,l:1,G:1},a=>"number"===typeof a);
u(0,"java.lang.Float",{Qa:1,A:1,a:1,k:1,l:1,G:1},a=>da(a));u(0,"java.lang.Integer",{Sa:1,A:1,a:1,k:1,l:1,G:1},a=>ca(a));u(0,"java.lang.Long",{Ta:1,A:1,a:1,k:1,l:1,G:1},a=>a instanceof k);function l(a){for(var b=a.length,c=0,d=0;d!==b;)c=((c<<5)-c|0)+a.charCodeAt(d)|0,d=1+d|0;return c}var va=u(0,"java.lang.String",{Ia:1,a:1,k:1,aa:1,l:1,G:1},a=>"string"===typeof a);function S(){}S.prototype=new p;S.prototype.constructor=S;function Xa(){}Xa.prototype=S.prototype;S.prototype.$=function(){return this.B()};
S.prototype.Y=function(a,b,c,d){return Aa(this,a,b,c,d)};function T(a){this.r=0;this.oa=a;this.O=0;this.r=a.g()}T.prototype=new Oa;T.prototype.constructor=T;T.prototype.o=function(){return this.r};T.prototype.e=function(){return 0<this.r};T.prototype.d=function(){if(0<this.r){var a=this.oa.f(this.O);this.O=1+this.O|0;this.r=-1+this.r|0;return a}return Na().I.d()};u(T,"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{ib:1,ea:1,ga:1,s:1,t:1,a:1});function Ya(){}Ya.prototype=new Xa;
Ya.prototype.constructor=Ya;function Za(){}Za.prototype=Ya.prototype;Ya.prototype.h=function(){return this.B()+"(\x3cnot computed\x3e)"};function U(){}U.prototype=new Xa;U.prototype.constructor=U;function $a(){}$a.prototype=U.prototype;
U.prototype.n=function(){Ja||(Ja=new G);var a=Ja;if(this&&this.$classData&&this.$classData.i.ma)a:{a=a.H;var b=this.g();switch(b){case 0:a=D(a^0);break a;case 1:a=D(C(a,A(B(),this.f(0)))^1);break a;default:var c=A(B(),this.f(0)),d=a=C(a,c),e=A(B(),this.f(1));c=e-c|0;for(var f=2;f<b;){a=C(a,e);var g=A(B(),this.f(f));if(c!==(g-e|0)||0===c){a=C(a,g);for(f=1+f|0;f<b;)a=C(a,A(B(),this.f(f))),f=1+f|0;a=D(a^b);break a}e=g;f=1+f|0}a=D(C(C(d,c),e))}}else if(this instanceof V){for(a=a.H;this!==I();)Wa();a=
D(a^0)}else a:if(b=a.H,a=this.j(),a.e())if(d=a.d(),a.e()){e=a.d();c=A(B(),d);d=b=C(b,c);e=A(B(),e);c=e-c|0;for(f=2;a.e();){b=C(b,e);g=A(B(),a.d());if(c!==(g-e|0)||0===c){b=C(b,g);for(f=1+f|0;a.e();)b=C(b,A(B(),a.d())),f=1+f|0;a=D(b^f);break a}e=g;f=1+f|0}a=D(C(C(d,c),e))}else a=D(C(b,A(B(),d))^1);else a=D(b^0);return a};U.prototype.h=function(){var a=this.$()+"(";if(0===this.o())a=""+a+")";else{var b=this.Y,c=new W;c.p=new P;a=b.call(this,c,a,", ",")").p.c}return a};function ab(){}ab.prototype=new Za;
ab.prototype.constructor=ab;function bb(){}bb.prototype=ab.prototype;function X(){this.T=null}X.prototype=new bb;X.prototype.constructor=X;function cb(){}cb.prototype=X.prototype;X.prototype.f=function(a){return this.T.f(a)};X.prototype.g=function(){return this.T.g()};function Y(a){this.T=a}Y.prototype=new cb;Y.prototype.constructor=Y;Y.prototype.j=function(){return new T(this)};Y.prototype.B=function(){return"IndexedSeqView"};Y.prototype.o=function(){return this.g()};
u(Y,"scala.collection.IndexedSeqView$Id",{hb:1,pb:1,eb:1,fb:1,N:1,P:1,s:1,R:1,t:1,Q:1,rb:1,a:1,ob:1,S:1,gb:1,na:1});function db(){}db.prototype=new $a;db.prototype.constructor=db;function eb(){}eb.prototype=db.prototype;function fb(){}fb.prototype=new $a;fb.prototype.constructor=fb;function gb(){}gb.prototype=fb.prototype;function hb(){}hb.prototype=new gb;hb.prototype.constructor=hb;function ib(){}ib.prototype=hb.prototype;function V(){}V.prototype=new eb;V.prototype.constructor=V;
function jb(){}jb.prototype=V.prototype;V.prototype.B=function(){return"LinearSeq"};V.prototype.f=function(a){return Ua(this,a)};V.prototype.g=function(){for(var a=0;this!==I();)a=1+a|0,Va();return a};V.prototype.$=function(){return"List"};function Z(){}Z.prototype=new jb;Z.prototype.constructor=Z;function Wa(){throw new Ta("head of empty list");}function Va(){throw new Ra("tail of empty list");}Z.prototype.o=function(){return 0};Z.prototype.j=function(){return Na().I};
u(Z,"scala.collection.immutable.Nil$",{xb:1,wb:1,sb:1,fa:1,N:1,P:1,s:1,R:1,t:1,Q:1,ha:1,ca:1,W:1,S:1,ba:1,yb:1,tb:1,zb:1,ub:1,mb:1,nb:1,vb:1,qb:1,qa:1,pa:1,Ab:1,ra:1,a:1,bb:1});var kb;function I(){kb||(kb=new Z);return kb}function W(){this.p=null}W.prototype=new gb;W.prototype.constructor=W;W.prototype.B=function(){return"IndexedSeq"};W.prototype.j=function(){return new T(new Y(this))};W.prototype.g=function(){return this.p.g()};W.prototype.o=function(){return this.p.g()};W.prototype.h=function(){return this.p.c};
W.prototype.f=function(a){return new h(this.p.c.charCodeAt(a))};u(W,"scala.collection.mutable.StringBuilder",{Jb:1,sa:1,fa:1,N:1,P:1,s:1,R:1,t:1,Q:1,ha:1,ca:1,W:1,S:1,ba:1,Ba:1,xa:1,Ca:1,va:1,L:1,Aa:1,ta:1,wa:1,ua:1,Db:1,ma:1,na:1,Eb:1,aa:1,a:1});function K(){this.ia=null;this.ya=this.U=0;this.ia=I();this.U=0}K.prototype=new ib;K.prototype.constructor=K;K.prototype.j=function(){return new R(Na().I,new N(()=>this.ya))};K.prototype.f=function(a){return Ua(this.ia,a)};K.prototype.g=function(){return this.U};
K.prototype.o=function(){return this.U};K.prototype.B=function(){return"ListBuffer"};u(K,"scala.collection.mutable.ListBuffer",{Fb:1,Bb:1,sa:1,fa:1,N:1,P:1,s:1,R:1,t:1,Q:1,ha:1,ca:1,W:1,S:1,ba:1,Ba:1,xa:1,Ca:1,va:1,L:1,Cb:1,wa:1,ua:1,Ib:1,qa:1,pa:1,Aa:1,ta:1,ra:1,a:1});aa=new k(0,0);wa.la=aa;va.w||(va.w=ua());new va.w.J([]);Ka||(Ka=new J);for(var lb=Ka.X.j();lb.e();)(0,lb.d().V)();
}).call(this);
//# sourceMappingURL=scaladoc-js-contributors-opt.js.map
