(function(){
'use strict';var f;function h(a){switch(typeof a){case "string":return"java.lang.String";case "number":return l(a)?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":m(a)?"java.lang.Float":"java.lang.Double";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return a instanceof n?"java.lang.Long":a&&a.$classData?a.$classData.name:null.H()}}var p=new DataView(new ArrayBuffer(8)),r=0,t=new WeakMap;
function aa(a){switch(typeof a){case "string":return u(a);case "number":var b=a|0;b===a&&-Infinity!==1/a?a=b:a!==a?a=2146959360:(p.setFloat64(0,a,!0),a=(p.getInt32(0,!0)|0)^(p.getInt32(4,!0)|0));return a;case "bigint":b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:u(a);default:if(null===a)return 0;b=t.get(a);void 0===b&&(r=b=r+1|0,t.set(a,
b));return b}}function l(a){return"number"===typeof a&&(a|0)===a&&1/a!==1/-0}function m(a){return"number"===typeof a&&(a!==a||Math.fround(a)===a)}function v(){}v.prototype.constructor=v;function w(){}w.prototype=v.prototype;v.prototype.n=function(){return aa(this)};v.prototype.m=function(){var a=this.n();return h(this)+"@"+(a>>>0).toString(16)};v.prototype.toString=function(){return this.m()};function x(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}
x.prototype=new w;x.prototype.constructor=x;function y(){}y.prototype=x.prototype;function z(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}z.prototype=new w;z.prototype.constructor=z;function A(a){this.a="number"===typeof a?new Uint16Array(a):a}A.prototype=new w;A.prototype.constructor=A;function B(a){this.a="number"===typeof a?new Int8Array(a):a}B.prototype=new w;B.prototype.constructor=B;function C(a){this.a="number"===typeof a?new Int16Array(a):a}
C.prototype=new w;C.prototype.constructor=C;function D(a){this.a="number"===typeof a?new Int32Array(a):a}D.prototype=new w;D.prototype.constructor=D;function E(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=f}else this.a=a}E.prototype=new w;E.prototype.constructor=E;function F(a){this.a="number"===typeof a?new Float32Array(a):a}F.prototype=new w;F.prototype.constructor=F;function G(a){this.a="number"===typeof a?new Float64Array(a):a}G.prototype=new w;
G.prototype.constructor=G;function H(){this.p=void 0;this.i=this.e=null;this.j=0;this.u=null;this.f="";this.g=this.h=void 0;this.name="";this.q=!1;this.k=void 0}function I(a,b,c,d){var e=new H;e.e={};e.u=a;e.f=b;e.g=k=>k===e;e.name=c;e.q=!0;e.k=()=>!1;void 0!==d&&(e.h=J(e,d));return e}
function K(a,b,c,d){var e=new H,k=Object.getOwnPropertyNames(c)[0];e.e=c;e.f="L"+b+";";e.g=g=>!!g.e[k];e.name=b;e.k=d||(g=>!!(g&&g.$classData&&g.$classData.e[k]));"number"!==typeof a&&(a.prototype.$classData=e);return e}function J(a,b,c){var d=new H;b.prototype.$classData=d;var e="["+a.f;d.p=b;d.e={z:1,b:1};d.i=a;d.j=1;d.f=e;d.name=e;d.g=c||(k=>d===k);d.k=k=>k instanceof b;return d}
function ba(){function a(g){if("number"===typeof g){this.a=Array(g);for(var q=0;q<g;q++)this.a[q]=null}else this.a=g}var b=L,c=new H;a.prototype=new y;a.prototype.constructor=a;a.prototype.$classData=c;var d=b.i||b,e=b.j+1;b="["+b.f;c.p=a;c.e={z:1,b:1};c.i=d;c.j=e;c.f=b;c.name=b;var k=g=>{var q=g.j;return q===e?d.g(g.i):q>e&&d===M};c.g=k;c.k=g=>{g=g&&g.$classData;return!!g&&(g===c||k(g))};return c}var M=new H;M.e={};M.f="Ljava.lang.Object;";M.g=a=>!a.q;M.name="java.lang.Object";M.k=a=>null!==a;
M.h=J(M,x,a=>{var b=a.j;return 1===b?!a.i.q:1<b});v.prototype.$classData=M;I(void 0,"V","void",void 0);I(!1,"Z","boolean",z);I(0,"C","char",A);I(0,"B","byte",B);I(0,"S","short",C);I(0,"I","int",D);var ca=I(null,"J","long",E);I(0,"F","float",F);I(0,"D","double",G);function N(){window.document.documentElement}N.prototype=new w;N.prototype.constructor=N;K(N,"dotty.tools.scaladoc.ContentContributors",{B:1});function O(){P=this}O.prototype=new w;O.prototype.constructor=O;
K(O,"java.lang.System$Streams$",{X:1});var P;K(0,"java.lang.Void",{Z:1},a=>void 0===a);function n(a,b){this.t=a;this.s=b}n.prototype=new w;n.prototype.constructor=n;n.prototype.n=function(){return this.t^this.s};
n.prototype.m=function(){da||(da=new Q);var a=this.t;var b=this.s;if(b===a>>31)b=""+a;else if(0===(-2097152&(b^b>>10)))b=""+(4294967296*b+(a>>>0));else{var c=b>>31,d=a^c;a=d-c|0;c=+Math.floor(1E-9*(4294967296*(((b^c)+((d&~a)>>>31|0)|0)>>>0)+(a>>>0)));a=a-Math.imul(1E9,c|0)|0;0>a?(--c,a=1E9+a|0):1E9<=a&&(c+=1,a=-1E9+a|0);a=""+a;c=""+c+"000000000".substring(a.length)+a;b=0>b?"-"+c:c}return b};K(n,"org.scalajs.linker.runtime.RuntimeLong",{E:1});function Q(){}Q.prototype=new w;
Q.prototype.constructor=Q;K(Q,"org.scalajs.linker.runtime.RuntimeLong$",{F:1});var da;function R(){}R.prototype=new w;R.prototype.constructor=R;K(R,"scala.util.CommandLineParser$",{ba:1});function S(a){this.A=a}S.prototype=new w;S.prototype.constructor=S;S.prototype.m=function(){return"DynamicVariable("+this.A+")"};K(S,"scala.util.DynamicVariable",{ca:1});
class ea extends Error{constructor(){super();this.r=null}m(){var a=h(this),b=this.r;return null===b?a:a+": "+b}n(){return v.prototype.n.call(this)}get message(){var a=this.r;return null===a?"":a}get name(){return h(this)}toString(){return this.m()}}function T(){P||(P=new O)}T.prototype=new w;T.prototype.constructor=T;K(T,"scala.Console$",{$:1,aa:1});class fa extends ea{}function U(){}U.prototype=new w;U.prototype.constructor=U;function V(){}V.prototype=U.prototype;
K(0,"java.lang.Boolean",{K:1,b:1,c:1,d:1},a=>"boolean"===typeof a);K(0,"java.lang.Character",{N:1,b:1,c:1,d:1},()=>!1);class ha extends fa{}function W(){}W.prototype=new V;W.prototype.constructor=W;function ia(){}ia.prototype=W.prototype;class ja extends ha{constructor(a){super();this.r=a;"[object Error]"!==Object.prototype.toString.call(this)&&(void 0===Error.captureStackTrace||Object.isSealed(this)?Error():Error.captureStackTrace(this))}}K(ja,"java.lang.ArithmeticException",{J:1,V:1,P:1,Y:1,b:1});
K(0,"java.lang.Byte",{L:1,l:1,b:1,c:1,d:1},a=>"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0);function X(){}X.prototype=new V;X.prototype.constructor=X;K(X,"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{T:1,x:1,v:1,y:1,w:1});K(0,"java.lang.Short",{W:1,l:1,b:1,c:1,d:1},a=>"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0);K(0,"java.lang.Double",{O:1,l:1,b:1,c:1,d:1,o:1},a=>"number"===typeof a);K(0,"java.lang.Float",{Q:1,l:1,b:1,c:1,d:1,o:1},a=>m(a));
K(0,"java.lang.Integer",{R:1,l:1,b:1,c:1,d:1,o:1},a=>l(a));K(0,"java.lang.Long",{U:1,l:1,b:1,c:1,d:1,o:1},a=>a instanceof n);function u(a){for(var b=a.length,c=0,d=0;d!==b;)c=((c<<5)-c|0)+a.charCodeAt(d)|0,d=1+d|0;return c}var L=K(0,"java.lang.String",{G:1,b:1,c:1,M:1,d:1,o:1},a=>"string"===typeof a);function Y(){}Y.prototype=new ia;Y.prototype.constructor=Y;function ka(){}ka.prototype=Y.prototype;function Z(){}Z.prototype=new ka;Z.prototype.constructor=Z;
K(Z,"java.lang.JSConsoleBasedPrintStream",{S:1,D:1,C:1,x:1,v:1,y:1,w:1,I:1});f=new n(0,0);ca.u=f;L.h||(L.h=ba());new L.h.p([]);try{new N}catch(a){throw a;};
}).call(this);
//# sourceMappingURL=scaladoc-js-contributors-opt.js.map
