(function(){
'use strict';function f(a){switch(typeof a){case "string":return"java.lang.String";case "number":return g(a)?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":k(a)?"java.lang.Float":"java.lang.Double";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return a&&a.$classData?a.$classData.name:null.D()}}var m=new DataView(new ArrayBuffer(8)),n=0,q=new WeakMap;
function aa(a){switch(typeof a){case "string":return r(a);case "number":var b=a|0;b===a&&-Infinity!==1/a?a=b:a!==a?a=2146959360:(m.setFloat64(0,a,!0),a=(m.getInt32(0,!0)|0)^(m.getInt32(4,!0)|0));return a;case "bigint":b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:r(a);default:if(null===a)return 0;b=q.get(a);void 0===b&&(n=b=n+1|0,q.set(a,
b));return b}}function g(a){return"number"===typeof a&&(a|0)===a&&1/a!==1/-0}function k(a){return"number"===typeof a&&(a!==a||Math.fround(a)===a)}function t(){}t.prototype.constructor=t;function u(){}u.prototype=t.prototype;t.prototype.p=function(){return aa(this)};t.prototype.n=function(){var a=this.p();return f(this)+"@"+(a>>>0).toString(16)};t.prototype.toString=function(){return this.n()};function v(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}
v.prototype=new u;v.prototype.constructor=v;function w(){}w.prototype=v.prototype;function x(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}x.prototype=new u;x.prototype.constructor=x;function y(a){this.a="number"===typeof a?new Uint16Array(a):a}y.prototype=new u;y.prototype.constructor=y;function z(a){this.a="number"===typeof a?new Int8Array(a):a}z.prototype=new u;z.prototype.constructor=z;function A(a){this.a="number"===typeof a?new Int16Array(a):a}
A.prototype=new u;A.prototype.constructor=A;function B(a){this.a="number"===typeof a?new Int32Array(a):a}B.prototype=new u;B.prototype.constructor=B;function C(a){this.a="number"===typeof a?new Int32Array(a<<1):a}C.prototype=new u;C.prototype.constructor=C;function D(a){this.a="number"===typeof a?new Float32Array(a):a}D.prototype=new u;D.prototype.constructor=D;function E(a){this.a="number"===typeof a?new Float64Array(a):a}E.prototype=new u;E.prototype.constructor=E;
function F(){this.o=void 0;this.i=this.e=null;this.j=0;this.f="";this.g=this.h=void 0;this.name="";this.q=!1;this.k=void 0}function G(a,b,d){var c=new F;c.e={};c.f=a;c.g=h=>h===c;c.name=b;c.q=!0;c.k=()=>!1;void 0!==d&&(c.h=H(c,d))}function I(a,b,d,c){var h=new F,l=Object.getOwnPropertyNames(d)[0];h.e=d;h.f="L"+b+";";h.g=e=>!!e.e[l];h.name=b;h.k=c||(e=>!!(e&&e.$classData&&e.$classData.e[l]));"number"!==typeof a&&(a.prototype.$classData=h);return h}
function H(a,b,d){var c=new F;b.prototype.$classData=c;var h="["+a.f;c.o=b;c.e={w:1,b:1};c.i=a;c.j=1;c.f=h;c.name=h;c.g=d||(l=>c===l);c.k=l=>l instanceof b;return c}
function ba(){function a(e){if("number"===typeof e){this.a=Array(e);for(var p=0;p<e;p++)this.a[p]=null}else this.a=e}var b=J,d=new F;a.prototype=new w;a.prototype.constructor=a;a.prototype.$classData=d;var c=b.i||b,h=b.j+1;b="["+b.f;d.o=a;d.e={w:1,b:1};d.i=c;d.j=h;d.f=b;d.name=b;var l=e=>{var p=e.j;return p===h?c.g(e.i):p>h&&c===K};d.g=l;d.k=e=>{e=e&&e.$classData;return!!e&&(e===d||l(e))};return d}var K=new F;K.e={};K.f="Ljava.lang.Object;";K.g=a=>!a.q;K.name="java.lang.Object";K.k=a=>null!==a;
K.h=H(K,v,a=>{var b=a.j;return 1===b?!a.i.q:1<b});t.prototype.$classData=K;G("V","void",void 0);G("Z","boolean",x);G("C","char",y);G("B","byte",z);G("S","short",A);G("I","int",B);G("J","long",C);G("F","float",D);G("D","double",E);function L(){window.document.documentElement}L.prototype=new u;L.prototype.constructor=L;I(L,"dotty.tools.scaladoc.ContentContributors",{y:1});function M(){N=this}M.prototype=new u;M.prototype.constructor=M;I(M,"java.lang.System$Streams$",{T:1});var N;
I(0,"java.lang.Void",{V:1},a=>void 0===a);function O(){}O.prototype=new u;O.prototype.constructor=O;I(O,"org.scalajs.linker.runtime.RuntimeLong$",{B:1});function P(){}P.prototype=new u;P.prototype.constructor=P;I(P,"scala.util.CommandLineParser$",{Y:1});function Q(a){this.x=a}Q.prototype=new u;Q.prototype.constructor=Q;Q.prototype.n=function(){return"DynamicVariable("+this.x+")"};I(Q,"scala.util.DynamicVariable",{Z:1});
class ca extends Error{constructor(){super();this.r=null}n(){var a=f(this),b=this.r;return null===b?a:a+": "+b}p(){return t.prototype.p.call(this)}get message(){var a=this.r;return null===a?"":a}get name(){return f(this)}toString(){return this.n()}}function R(){N||(N=new M)}R.prototype=new u;R.prototype.constructor=R;I(R,"scala.Console$",{W:1,X:1});class da extends ca{}function S(){}S.prototype=new u;S.prototype.constructor=S;function T(){}T.prototype=S.prototype;
I(0,"java.lang.Boolean",{G:1,b:1,c:1,d:1},a=>"boolean"===typeof a);I(0,"java.lang.Character",{J:1,b:1,c:1,d:1},()=>!1);class ea extends da{}function U(){}U.prototype=new T;U.prototype.constructor=U;function V(){}V.prototype=U.prototype;class fa extends ea{constructor(a){super();this.r=a;"[object Error]"!==Object.prototype.toString.call(this)&&(void 0===Error.captureStackTrace||Object.isSealed(this)?Error():Error.captureStackTrace(this))}}I(fa,"java.lang.ArithmeticException",{F:1,R:1,L:1,U:1,b:1});
I(0,"java.lang.Byte",{H:1,l:1,b:1,c:1,d:1},a=>"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0);function W(){}W.prototype=new T;W.prototype.constructor=W;I(W,"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{P:1,u:1,s:1,v:1,t:1});I(0,"java.lang.Short",{S:1,l:1,b:1,c:1,d:1},a=>"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0);I(0,"java.lang.Double",{K:1,l:1,b:1,c:1,d:1,m:1},a=>"number"===typeof a);I(0,"java.lang.Float",{M:1,l:1,b:1,c:1,d:1,m:1},a=>k(a));
I(0,"java.lang.Integer",{N:1,l:1,b:1,c:1,d:1,m:1},a=>g(a));I(0,"java.lang.Long",{Q:1,l:1,b:1,c:1,d:1,m:1},()=>!1);function r(a){for(var b=a.length,d=0,c=0;c!==b;)d=((d<<5)-d|0)+a.charCodeAt(c)|0,c=1+c|0;return d}var J=I(0,"java.lang.String",{C:1,b:1,c:1,I:1,d:1,m:1},a=>"string"===typeof a);function X(){}X.prototype=new V;X.prototype.constructor=X;function Y(){}Y.prototype=X.prototype;function Z(){}Z.prototype=new Y;Z.prototype.constructor=Z;
I(Z,"java.lang.JSConsoleBasedPrintStream",{O:1,A:1,z:1,u:1,s:1,v:1,t:1,E:1});J.h||(J.h=ba());new J.h.o([]);try{new L}catch(a){throw a;};
}).call(this);
//# sourceMappingURL=scaladoc-js-contributors-opt.js.map
