[versions]
agp = "8.7.3"
kotlin = "2.0.20"
junit = "4.13.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
