= The Mill Meta-Build
:page-aliases: The_Mill_Meta_Build.adoc



The meta-build manages the compilation of the `build.mill`.
Customizing the meta-build gives you greater control over how exactly your
`build.mill` evaluates. The meta-build lives in the `mill-build/` directory,
and needs to contain a top-level module of type `MillBuildRootModule`.

If you don't configure it explicitly, a built-in synthetic meta-build is used.
Meta-builds are recursive, which means they can themselves have nested meta-builds, and so on.

To run a task on a meta-build, you specify the `--meta-level` option to select
the meta-build level.

== Autoformatting the `build.mill`

As an example of running a task on the meta-build, you can format the `build.mill` with Scalafmt.
Everything is already provided by Mill.
You only need a `.scalafmt.conf` config file which at least needs configure the Scalafmt version.

.Run Scalafmt on the `build.mill` (and potentially included files)
----
$ mill --meta-level 1 mill.scalalib.scalafmt/
----

* `--meta-level 1` selects the first meta-build. Without any customization, this is the only built-in meta-build.
* `mill.scalalib.scalafmt/reformatAll` is a generic task to format scala source files with Scalafmt. It requires the tasks that refer to the source files as argument
* `sources` this selects the `sources` tasks of the meta-build, which at least contains the `build.mill`.

== Finding plugin updates

Mill plugins are defined as `mvnDeps` in the meta-build.
Hence, you can easily search for updates with the external `mill.scalalib.Dependency` module.

.Check for Mill Plugin updates
----
$ mill --meta-level 1 mill.scalalib.Dependency/showUpdates
Found 1 dependency update for
de.tototec:de.tobiasroeser.mill.vcs.version_mill0.11_2.13 : 0.3.1-> 0.4.0
----

== Sharing Libraries between `build.mill` and Application Code

include::partial$example/extending/metabuild/4-meta-build.adoc[]

== Sharing Source Code between `build.mill` and Application Code

include::partial$example/extending/metabuild/5-meta-shared-sources.adoc[]