= Kotlin Build Examples
:page-aliases: Kotlin_Build_Examples.adoc
++++
<script>
gtag('config', 'AW-16649289906');
</script>
++++

On this page, we will explore the Mill build tool via a series of simple Kotlin
example projects. Each project demonstrates one particular feature of the Mill
build tool, and is also an executable codebase you can download and run. By the
end of this page, you will be familiar with how to configure Mill to work with
realistic Kotlin codebases: cross-building, testing, and publishing them.


Many of the APIs covered here are listed in the API documentation:

* {mill-doc-url}/api/latest/mill/main/RootModule.html[`mill.kotlinlib.RootModule`]
* {mill-doc-url}/api/latest/mill/scalalib/TestModule$.html[`mill.kotlinlib.TestModule`]
* {mill-doc-url}/api/latest/mill/scalalib/PublishModule.html[`mill.kotlinlib.PublishModule`]
* {mill-doc-url}/api/latest/mill/kotlinlib/KotlinMavenModule.html[`mill.kotlinlib.KotlinMavenModule`]
* {mill-doc-url}/api/latest/mill/kotlinlib/KotlinModule.html[`mill.kotlinlib.KotlinModule`]

== Nesting Modules

include::partial$example/kotlinlib/builds/1-nested-modules.adoc[]

== Maven-Compatible Modules

include::partial$example/kotlinlib/builds/2-compat-modules.adoc[]


== Realistic Kotlin Example Project

include::partial$example/kotlinlib/builds/4-realistic.adoc[]

