= Spotless Configuration

Mill configures https://github.com/diffplug/spotless/[Spotless] formatters using a custom JSON configuration.

NOTE: Unless specified otherwise, JSON fields are optional and can be omitted.

The root of the configuration has the following fields:

[source,json]
----
{
  "formatters": [],
  "excludes": []
}
----

- `formatters`: one or more <<_formatter>> configurations, typically one for each language
- `excludes`: zero or more https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)[path matcher] values for files to skip, eg. `pass:[glob:**/.git/**/*]`

NOTE: You do not have to add a matcher to exclude Mill `out` folder, it is always excluded.

== Formatter

[source,json]
----
{
  "includes": [],
  "steps": [],
  "lineEnding": "GIT_ATTRIBUTES_FAST_ALLSAME",
  "encoding": "UTF-8",
  "lintSuppressions": []
}
----

- `includes`: one or more https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)[path matcher] values for files to format, eg. `pass:[glob:**/*.java]`
- `steps`: one or more <<_formatter_step>> configurations
- `lineEnding`: file https://github.com/diffplug/spotless/tree/main/plugin-gradle#line-endings-and-encodings-invisible-stuff[line endings]
- `encoding`: file https://github.com/diffplug/spotless/tree/main/plugin-gradle#line-endings-and-encodings-invisible-stuff[character encoding]
- `lintSuppressions`: zero or more <<_lint_suppression>> configurations

CAUTION: Formatted output is sensitive to the order of `steps`.

NOTE: Lints must be https://github.com/diffplug/spotless/tree/main/plugin-gradle#linting[fixed or suppressed].

== Formatter Step

NOTE: Field `$type` is required.

=== https://github.com/diffplug/spotless/tree/main/plugin-gradle#java[Java]

==== https://github.com/diffplug/spotless/tree/main/plugin-gradle#palantir-java-format[PalantirJavaFormat]

[source,json]
----
{
  "$type": "PalantirJavaFormat",
  "version": null,
  "style": null,
  "formatJavadoc": false
}
----

==== https://github.com/diffplug/spotless/tree/main/plugin-gradle#formatAnnotations[FormatAnnotations]

[source,json]
----
{
  "$type": "FormatAnnotations",
  "addedTypeAnnotations": [],
  "removedTypeAnnotations": []
}
----

NOTE: This step should be added after a Java formatter.

=== https://github.com/diffplug/spotless/tree/main/plugin-gradle#kotlin[Kotlin]

==== https://github.com/diffplug/spotless/tree/main/plugin-gradle#ktfmt[Ktfmt]

[source,json]
----
{
  "$type": "Ktfmt",
  "version": null,
  "style": null,
  "maxWidth": null,
  "blockIndent": null,
  "continuationIndent": null,
  "removeUnusedImports": null,
  "manageTrailingCommas": null
}
----

- `style`: https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/kotlin/KtfmtStep.java[KtfmtStep.Style]

==== https://github.com/diffplug/spotless/tree/main/plugin-gradle#ktlint[KtLint]

[source,json]
----
{
  "$type": "KtLint",
  "version": null,
  "configFile": ".editorconfig",
  "customRuleSets": []
}
----

=== https://github.com/diffplug/spotless/tree/main/plugin-gradle#scala[Scala]

==== https://github.com/diffplug/spotless/tree/main/plugin-gradle#scalafmt[Scalafmt]

[source,json]
----
{
  "$type": "Scalafmt",
  "version": null,
  "scalaMajorVersion": null,
  "configFile": ".scalafmt.conf"
}
----

=== https://github.com/diffplug/spotless/tree/main/plugin-gradle#generic-steps[Generic]

==== Fence

A fence is used to preserve/apply formatting within matching blocks is specified with the following (required) fields:

- `name`: name of the fence
- `regex`: regular expression for matching blocks specified as `[pattern]` or `[open, close`] markers.
- `preserve`: preserve/apply `steps` within matching blocks
- `steps`: one or more <<_formatter_step>> to apply outside/inside matching blocks

A common use case is to preserve existing formatting within a https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson[toggle].
The <<_formatter>> configuration below shows how to turn off formatting within blocks in Scala files.

[source,json]
----
{
  "includes": ["glob:**/*.scala"],
  "steps": [
    {
      "$type": "Fence",
      "name": "toggle",
      "regex": ["spotless:off", "spotless:on"],
      "preserve": true,
      "steps": [
        {
          "$type": "Scalafmt"
        }
      ]
    }
  ]
}
----

An alternate use case is formatting
https://github.com/diffplug/spotless/tree/main/plugin-gradle#inception-languages-within-languages-within[languages within languages].
The <<_formatter>> configuration below shows how to configure formatting for Java code in Scala files.

[source,json]
----
{
  "includes": ["glob:**/*.scala"],
  "steps": [
    {
      "$type": "Scalafmt"
    },
    {
      "$type": "Fence",
      "name": "java example",
      "regex": ["```java", "```"],
      "preserve": false,
      "steps": [
        {
          "$type": "PalantirJavaFormat"
        }
      ]
    }
  ]
}
----

==== https://github.com/diffplug/spotless/tree/main/plugin-gradle#license-header[LicenseHeader]

[source,json]
----
{
  "$type": "LicenseHeader",
  "header": null,
  "headerFile": "LICENSE",
  "delimiter": "(package|import|public|class|module) ",
  "name": null,
  "contentPattern": null,
  "yearSeparator": null,
  "yearMode": null,
  "skipLinesMatching": null
}
----

NOTE: This step is typically the last one applied.

== Lint Suppression

Lints can be suppressed using a combination of the following (optional) fields:

- `path`: path of file (relative to workspace) to suppress lints for
- `step`: name of <<_formatter_step>> to suppress lints for
- `shortCode`: identity of lint to suppress

Typical usage is shown below.

[source,json]
----
{
  "step": "ktlint",
  "shortCode": "standard:no-wildcard-imports"
}
----

CAUTION: Omitting all fields will suppress all lints.
