# action.yml
inputs:
  millargs:
    default: ''
    type: string

  coursierarchive:
    default: ''
    type: string

  install-android-sdk:
    default: false
    type: boolean
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with: { node-version: '22' }

    - run: ./mill -i -k selective.resolve ${{ inputs.millargs }}
      shell: bash

    - run: cat out/mill-build/methodCodeHashSignatures.dest/current/spanningInvalidationTree.json
      shell: bash

    - run: ./mill -i -k selective.resolveTree ${{ inputs.millargs }}
      shell: bash

    - run: ./mill -i -k selective.resolveChanged ${{ inputs.millargs }}
      shell: bash

    - run: ./mill -i -j1 -k selective.run ${{ inputs.millargs }}
      if: ${{ inputs.install-android-sdk }}
      env:
        COURSIER_ARCHIVE_CACHE: ${{ inputs.coursierarchive }}
      shell: bash

    - run: ./mill -i -k selective.run ${{ inputs.millargs }}
      if: ${{ !inputs.install-android-sdk }}
      env:
        COURSIER_ARCHIVE_CACHE: ${{ inputs.coursierarchive }}
      shell: bash

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: always() # always run even if the previous step fails
      with:
        fail_on_failure: false
        include_passed: false
        detailed_summary: true
        annotate_only: true
        require_tests: false
        report_paths: 'out/**/test-report.xml'
