# action.yml
inputs:
  millargs:
    default: ''
    type: string

  shell:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with: { node-version: '22' }

    - run: cat .mill-jvm-version
      shell: ${{ inputs.shell }}

    - run: ./mill -i -k selective.resolve ${{ inputs.millargs }}
      shell: ${{ inputs.shell }}

    # This generates a lot of logs and slows down the github actions UI like crazy, 
    # so only uncomment it when really necessary
    #- run: cat out/mill-build/codeSignatures.dest/current/spanningInvalidationTree.json
    #  shell: bash

    - run: ./mill -i -k dist.native.nativeImageMaybeCopyGraal
      shell: ${{ inputs.shell }}

    - run: ./mill -i -k selective.resolveTree ${{ inputs.millargs }}
      shell: ${{ inputs.shell }}

    # Comment this out because it can be very verbose when broad codesig
    # invalidation results in all tasks being counted as changed inputs
    #- run: ./mill -i -k selective.resolveChanged ${{ inputs.millargs }}
    #  shell: ${{ inputs.shell }}

    - run: ./mill -i -k selective.run ${{ inputs.millargs }}
      shell: ${{ inputs.shell }}

    - name: Clean-up Test Reports
      if: always() # always run even if the previous step fails
      # reports under 'sandbox' directories are generated by test cases themselves,
      # and might contains expected failures, that it makes no sense to report here
      # (these make GitHub mark the whole job as failed)
      run: rm -f $(find out -name test-report.xml | grep sandbox)
      shell: bash

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: always() # always run even if the previous step fails
      with:
        fail_on_failure: false
        include_passed: false
        detailed_summary: true
        annotate_only: true
        require_tests: false
        report_paths: 'out/**/test-report.xml'
