= Extending Mill
:link-ammonite: https://ammonite.io/

There are different ways of extending Mill, depending on how much customization
and flexibility you need. This page will go through your options from the
easiest/least-flexible to the hardest/most-flexible.

== import $file and import $ivy

include::example/misc/3-import-file-ivy.adoc[]

== The Mill Meta-Build

The meta-build manages the compilation of the `build.sc`.
If you don't configure it explicitly, a built-in synthetic meta-build is used.

To customize it, you need to explicitly enable it with `import $meta._`.
Once enabled, the meta-build lives in the `mill-build/` directory.
It needs to contain a top-level module of type `MillBuildRootModule`.

Meta-builds are recursive, which means, it can itself have a nested meta-builds, and so on.

To run a task on a meta-build, you specifying the `--meta-level` option to select the meta-build level.

=== Example: Format the `build.sc`

As an example of running a task on the meta-build, you can format the `build.sc` with Scalafmt.
Everything is already provided by Mill.
You only need a `.scalafmt.conf` config file which at least needs configure the Scalafmt version.

.Run Scalafmt on the `build.sc` (and potentially included files)
----
$ mill --meta-level 1 mill.scalalib.scalafmt.ScalafmtModule/reformatAll sources
----

* `--meta-level 1` selects the first meta-build. Without any customization, this is the only built-in meta-build.
* `mill.scalalib.scalafmt.ScalafmtModule/reformatAll` is a generic task to format scala source files with Scalafmt. It requires the targets that refer to the source files as argument
* `sources` this selects the `sources` targets of the meta-build, which at least contains the `build.sc`.

=== Example: Find plugin updates

Mill plugins are defined as `ivyDeps` in the meta-build.
Hence, you can easily search for updates with the external `mill.scalalib.Dependency` module.

.Check for Mill Plugin updates
----
$ mill --meta-level 1 mill.scalalib.Dependency/showUpdates
----

=== Example: Customizing the Meta-Build

include::example/misc/4-mill-build-folder.adoc[]

== Using ScalaModule.run as a task

include::example/misc/5-module-run-task.adoc[]

== Evaluator Commands (experimental)

_Evaluator Command are experimental and suspected to change.
See {mill-github-url}/issues/502[issue #502] for details._

You can define a command that takes in the current `Evaluator` as an argument,
which you can use to inspect the entire build, or run arbitrary tasks.
For example, here is the `mill.scalalib.GenIdea/idea` command which uses this
to traverse the module-tree and generate an Intellij project config for your
build.

[source,scala]
----
def idea(ev: Evaluator) = T.command {
  mill.scalalib.GenIdea(
    implicitly,
    ev.rootModule,
    ev.discover
  )
}
----

Many built-in tools are implemented as custom evaluator commands:
xref:Builtin_Commands.adoc#_inspect[inspect],
xref:Builtin_Commands.adoc#_resolve[resolve],
xref:Builtin_Commands.adoc#_show[show].
If you want a way to run Mill commands and programmatically manipulate the
tasks and outputs, you do so with your own evaluator command.
