
// Author Notes:
//
// This is the first page a user is expected to land on when learning about
// Mill. It is designed to be a quick, broad overview to get someone started:
// what is Mill, why should they care, and what some simple Mill builds look
// like and how to use them. We intentionally touch shallowly on a lot of
// topics without giving them a proper discussion, since the other pages have
// plenty of space to go in-depth.
//
// By the end of this page, a prospective Mill user should be familiar with
// what Mill is, hopefully have downloaded an example to try out, and be
// interested in learning more about the Mill build tool

= Introduction to Mill for Java


{mill-github-url}[Mill] is your shiny new Java build tool! Mill aims for
simplicity by reusing concepts you are already familiar with, borrowing ideas
from modern tools like https://maven.apache.org/[Maven], https://gradle.org/[Gradle],
https://bazel.build/[Bazel]. It lets you build
your projects in a way that's simple, fast, and predictable.

Compared to Maven and Gradle, Mill builds are far more intuitive and easy to read and write:

* **Mill builds are an order of magnitude more concise than Maven pom.xml files**: this makes
  them both easy to write and easy to read at a glance

* **Mill builds are easy to extend by non-experts**: anyone can extend a Mill build
  with a few lines of code, without needing to learn a complicated plugin framework,
  allowing end users the freedom to fit their build logic to their own unique requirements

* **Mill builds are familiar to anyone who knows programming**: rather than scopes, lifecycles,
  or phases, Mill builds on top of objects, methods, inheritance, and overrides: concepts
  immediately familiar to any Java programmer

include::partial$Intro_to_Mill_Header.adoc[]


== Simple Java Module

include::example/basicjava/1-simple.adoc[]

== Custom Build Logic

include::example/basicjava/2-custom-build-logic.adoc[]

== Multi-Module Project

include::example/basicjava/3-multi-module.adoc[]



include::partial$Intro_to_Mill_Footer.adoc[]