// Author Notes:
//
// This is the first page a user is expected to land on when learning about
// Mill. It is designed to be a quick, broad overview to get someone started:
// what is Mill, why should they care, and what some simple Mill builds look
// like and how to use them. We intentionally touch shallowly on a lot of
// topics without giving them a proper discussion, since the other pages have
// plenty of space to go in-depth.
//
// By the end of this page, a prospective Mill user should be familiar with
// what Mill is, hopefully have downloaded an example to try out, and be
// interested in learning more about the Mill build tool

= Introduction to Mill for Scala

:page-aliases: index.adoc, Intro_to_Mill.adoc

{mill-github-url}[Mill] is your shiny new Scala build tool! Mill aims for
simplicity by reusing concepts you are already familiar with, borrowing ideas
from modern tools like https://maven.apache.org/[Maven], https://gradle.org/[Gradle],
https://bazel.build/[Bazel] and https://www.scala-sbt.org/[SBT]. Mill lets you build
and customize your projects in a way that's simple, fast, and predictable.

Mill automates dealing with a lot of common build-tool concerns such as caching,
incremental re-computation, and parallelism. This allows you
to focus your effort on the business logic unique to your build, while letting
Mill take care of all the rest.

Compared to SBT and other tools, Mill builds are far more intuitive and easy to read,
write, and debug:

include::partial$Intro_to_Mill_Header.adoc[]

The following blog posts discuss some of the fundamental design issues with SBT, and
how Mill attempts to do better:

- https://www.lihaoyi.com/post/SowhatswrongwithSBT.html[So, what's wrong with SBT?]
- https://www.lihaoyi.com/post/MillBetterScalaBuilds.html[Mill: Better Scala Builds]

If you are using Mill, you will find the following book by the Author useful in
using Mill and its supporting libraries to the fullest:

* https://handsonscala.com/[Hands-on Scala Programming]

== Simple Scala Module

include::example/basic/1-simple.adoc[]

== Custom Build Logic

include::example/basic/2-custom-build-logic.adoc[]

== Multi-Module Project

include::example/basic/3-multi-module.adoc[]


include::partial$Intro_to_Mill_Footer.adoc[]
