
// Author Notes:
//
// This is the first page a user is expected to land on when learning about
// Mill. It is designed to be a quick, broad overview to get someone started:
// what is Mill, why should they care, and what some simple Mill builds look
// like and how to use them. We intentionally touch shallowly on a lot of
// topics without giving them a proper discussion, since the other pages have
// plenty of space to go in-depth.
//
// By the end of this page, a prospective Mill user should be familiar with
// what Mill is, hopefully have downloaded an example to try out, and be
// interested in learning more about the Mill build tool

= Introduction to Mill for Java
:page-aliases: index.adoc, Intro_to_Mill.adoc, Intro_to_Mill_for_Java.adoc

++++
<script>
gtag('config', 'AW-16649289906');
</script>
++++



:language: Java

include::partial$Intro_to_Mill_Header.adoc[]

Mill is used to build some real-world Java projects, such as the
https://github.com/swaldman/c3p0[C3P0 JDBC Connection Pool], and
can be used for applications built on top of common Java frameworks like
xref:Java_Web_Build_Examples.adoc#_spring_boot_todomvc_app[Spring Boot] or
xref:Java_Web_Build_Examples.adoc#_micronaut_todomvc_app[Micronaut].

Mill borrows ideas from other tools like https://maven.apache.org/[Maven],
https://gradle.org/[Gradle], https://bazel.build/[Bazel], but tries to learn from the
strengths of each tool and improve on their weaknesses. Although Maven and Gradle
are mature widely-used tools, they have fundamental limitations in their design
(https://blog.ltgt.net/maven-is-broken-by-design/[Maven Design],
https://www.bruceeckel.com/2021/01/02/the-problem-with-gradle/[Gradle Design]) that make
them difficult to improve upon incrementally.

Compared to Maven:

* **Mill follows Maven's innovation of good built-in defaults**: Mill's built-in
  ``JavaModule``s follow Maven's "convention over configuration" style. Small mill
  projects require minimal effort to get started, and larger Mill projects have a consistent
  structure building on these defaults.

* **Mill makes customizing the build tool much easier than Maven**. Projects usually
  grow beyond just compiling a single language: needing custom
  code generation, linting workflows, output artifacts, or support for
  additional languages. Mill makes doing this yourself easy, so you are not beholden
  to third-party plugins that may not exist, be well maintained, or interact well with each other.

* **Mill automatically caches and parallelizes your build**: Not just the
  built-in tasks that Mill ships with, but also any custom tasks or modules.
  This maximizes performance and snappiness of
  your command-line build workflows, and especially matters in larger codebases where builds
  tend to get slow: a Maven `clean install` taking over a minute might take just a 
  few seconds in Mill.

Compared to Gradle:

* **Mill follows Gradle's conciseness**: Rather than pages and pages of verbose XML, every
  line in a Mill build is meaningful. e.g. adding a dependency is 1 line in
  Mill, like it is in Gradle, and unlike the 5 line `<dependency>` declaration you find in Maven.
  Skimming and understanding a 100-line Mill `build.sc` file is
  often much easier than skimming the equivalent 500-line Maven `pom.xml`.

* **Mill builds are more easily understandable**: While the impact of a Gradle config change can
  be hard to determine at a glance, the impact of a Mill config change is localized,
  only affecting downstream tasks. Your IDE can navigate Mill's
  xref:Tasks.adoc[task graph] and xref:Modules.adoc[module tree] just as easily as it can
  navigate the method call graph in a normal Java program, something impossible in tools like
  Maven or Gradle.

* **Mill enforces best practices by default**. All Mill tasks are cached by default, even
  custom tasks. All Mill tasks write their output to disk xref:Out_Dir.adoc[a
  standard place]. All task inter-dependencies are automatically captured, without
  needing manual annotation. All Mill builds are incremental, not just tasks but also
  xref:The_Mill_Evaluation_Model.adoc#_caching_at_each_layer_of_the_evaluation_model[configuration
  and other phases]. Where Gradle requires considerable
  https://docs.gradle.org/current/userguide/incremental_build.html[effort and expertise]
  to maintain your build, Mill automates it so the
  easiest thing to do is almost always the right thing to do.

Mill build files are written in Scala, but you do not need to have prior experience
in Scala to read or write them. Like Gradle Groovy or Maven XML, it's easy to learn
enough Scala for Mill without needing to become an expert in the language.


include::partial$Intro_to_Mill_BlogVideo.adoc[]

== Simple Java Module

include::example/basicjava/1-simple.adoc[]

== Custom Build Logic

include::example/basicjava/2-custom-build-logic.adoc[]

== Multi-Module Project

include::example/basicjava/3-multi-module.adoc[]

include::partial$Intro_to_Mill_Footer.adoc[]
