= Java Module Configuration

++++
<script>
gtag('config', 'AW-16649289906');
</script>
++++

This page goes into more detail about the various configuration options
for `JavaModule`.

Many of the APIs covered here are listed in the API documentation:

* {mill-doc-url}/api/latest/mill/scalalib/JavaModule.html[mill.javaalib.JavaModule]


== Compilation & Execution Flags

include::example/javamodule/1-compilation-execution-flags.adoc[]

== Adding Ivy Dependencies

include::example/javamodule/2-ivy-deps.adoc[]

== Runtime and Compile-time Dependencies

include::example/javamodule/3-run-compile-deps.adoc[]

== Test Dependencies

include::example/javamodule/4-test-deps.adoc[]


== Javadoc Config

include::example/javamodule/6-docjar.adoc[]

== Unmanaged Jars

include::example/javamodule/7-unmanaged-jars.adoc[]

== Specifying the Main Class

include::example/javamodule/8-main-class.adoc[]

== Downloading Non-Maven Jars

include::example/javamodule/9-downloading-non-maven-jars.adoc[]

== Customizing the Assembly

include::example/javamodule/10-assembly-config.adoc[]

== Repository Config

include::example/javamodule/11-repository-config.adoc[]

== Maven Central: Blocked!

Under some circumstances (e.g. corporate firewalls), you may not have access maven central. The typical symptom will be error messages which look like this;

----
1 targets failed
mill.scalalib.ZincWorkerModule.classpath
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi:mill-scalalib-worker_2.13:0.11.1
        not found: C:\Users\partens\.ivy2\local\com.lihaoyi\mill-scalalib-worker_2.13\0.11.1\ivys\ivy.xml
        download error: Caught java.io.IOException (Server returned HTTP response code: 503 for URL: https://repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-worker_2.13/0.11.1/mill-scalalib-worker_2.13-0.11.1.pom) while downloading https://repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-worker_2.13/0.11.1/mill-scalalib-worker_2.13-0.11.1.pom
----

It is expected that basic commands (e.g. clean) will not work, as Mill saying it is unable to resolve it's own, fundamental, dependencies. Under such circumstances, you will normally have access to some proxy, or other corporate repository which resolves maven artefacts. The strategy is simply to tell mill to use that instead.

The idea is to set an environment variable COURSIER_REPOSITORIES (see coursier docs). The below command should set the environment variable for the current shell, and then run the mill command.

----
 COURSIER_REPOSITORIES=https://packages.corp.com/artifactory/maven/ mill resolve _
----

If you are using millw, a more permanent solution could be to set the environment variable at the top of the millw script, or as a user environment variable etc.

