= Java Build Examples

++++
<script>
gtag('config', 'AW-16649289906');
</script>
++++

On this page, we will explore the Mill build tool via a series of simple Java
example projects. Each project demonstrates one particular feature of the Mill
build tool, and is also an executable codebase you can download and run. By the
end of this page, you will be familiar with how to configure Mill to work with
realistic Java codebases: cross-building, testing, and publishing them.


Many of the APIs covered here are listed in the API documentation:

* {mill-doc-url}/api/latest/mill/main/RootModule.html[`mill.scalalib.RootModule`]
* {mill-doc-url}/api/latest/mill/scalalib/TestModule$.html[`mill.scalalib.TestModule`]
* {mill-doc-url}/api/latest/mill/scalalib/PublishModule.html[`mill.scalalib.PublishModule`]
* {mill-doc-url}/api/latest/mill/scalalib/MavenModule.html[`mill.scalalib.MavenModule`]
* {mill-doc-url}/api/latest/mill/scalalib/JavaModule.html[`mill.scalalib.JavaModule`]

== Common Configuration Overrides

include::example/javalib/builds/1-common-config.adoc[]

== Custom Tasks

include::example/javalib/builds/2-custom-tasks.adoc[]

== Overriding Tasks

include::example/javalib/builds/3-override-tasks.adoc[]

== Nesting Modules

include::example/javalib/builds/4-nested-modules.adoc[]

== Publish Module

include::example/javalib/builds/6-publish-module.adoc[]


== Maven-Compatible Modules

include::example/javalib/builds/8-compat-modules.adoc[]


== Realistic Java Example Project

include::example/javalib/builds/9-realistic.adoc[]


== Example Builds for Real Projects

Mill comes bundled with example builds for real-world open-source projects,
demonstrating how Mill can be used to build code outside of tiny example codebases:

=== JimFS

include::example/thirdparty/jimfs.adoc[]

=== Apache Commons IO

include::example/thirdparty/commons-io.adoc[]

== Real World Mill Builds

=== C3P0

https://github.com/swaldman/c3p0[C3P0] is a JDBC connection pooling library
written in Java, built using the Mill build tool.
