
// Author Notes:
//
// This is the first page a user is expected to land on when learning about
// Mill. It is designed to be a quick, broad overview to get someone started:
// what is Mill, why should they care, and what some simple Mill builds look
// like and how to use them. We intentionally touch shallowly on a lot of
// topics without giving them a proper discussion, since the other pages have
// plenty of space to go in-depth.
//
// By the end of this page, a prospective Mill user should be familiar with
// what Mill is, hopefully have downloaded an example to try out, and be
// interested in learning more about the Mill build tool

= Introduction to Mill for Java

:page-aliases: index.adoc, Intro_to_Mill.adoc, Intro_to_Mill_for_Java.adoc

:language: Java

include::partial$Intro_to_Mill_Header.adoc[]

Mill is used to build some real-world Java projects, such as the
https://github.com/swaldman/c3p0[C3P0 JDBC Connection Pool].

Mill borrows ideas from other tools like https://maven.apache.org/[Maven],
https://gradle.org/[Gradle], https://bazel.build/[Bazel], but tries to learn from the
strengths of each tool and improve on their weaknesses. Although Maven and Gradle
are mature widely-used tools, they have fundamental limitations in their design
(https://blog.ltgt.net/maven-is-broken-by-design/[Maven Design],
https://www.bruceeckel.com/2021/01/02/the-problem-with-gradle/[Gradle Design]) that make
them difficult to improve upon incrementally.

Compared to Maven:

* **Mill follows Maven's innovation of good built-in defaults**: Mill's built-in
  ``JavaModule``s follow Maven's "convention over configuration" style. This provides an
  excellent default template that can be used to structure your project without any custom
  configuration.

* **Mill makes customizing the build tool much easier than Maven**. As projects grow, build
  grow beyond just compiling a single language: you need custom
  code generation, custom linting workflows, custom output artifacts, or support for
  additional programming languages. Mill makes doing this yourself easy, so you are not beholden
  to third-party plugins that may not exist, be well maintained, or interact well with each other.

* **Mill automatically caches and parallelizes your build**: This applies not just to the
  built-in ``JavaModule``s and tasks that Mill ships with, but also any custom logic the
  developer may configure in their Mill build. This maximizes performance and snappiness of
  your command-line build workflows, and especially matters in larger codebases where builds
  tend to get slow.

Compared to Gradle:

* **Mill follows Gradle's conciseness**: Rather than pages and pages of verbose XML, every
  line of configuration in a Mill build is meaningful. e.g. adding a dependency is 1 line in
  Mill, like it is in Gradle, and unlike the 5 line `<dependency>` declaration you find in Maven

* **Mill helps keep your build understandable**: Unlike Gradle config statements that can
  work in mysterious ways, Mill build configuration is done via vanilla methods, objects,
  inheritance, and overrides. This means that impact of a Mill config statement is localized,
  without "_spooky action at a distance_", and the exact meaning of any config statement is
  a single "_jump-to-definition_" away in your IDE.

Mill can be used for applications built on top of common Java frameworks like
xref:Java_Web_Build_Examples.adoc#_spring_boot_todomvc_app[Spring Boot] or
xref:Java_Web_Build_Examples.adoc#_micronaut_todomvc_app[Micronaut].

Mill build files are written in Scala, but you do not need to have prior experience
in Scala to read or write them.


include::partial$Intro_to_Mill_BlogVideo.adoc[]

== Simple Java Module

include::example/basicjava/1-simple.adoc[]

== Custom Build Logic

include::example/basicjava/2-custom-build-logic.adoc[]

== Multi-Module Project

include::example/basicjava/3-multi-module.adoc[]

include::partial$Intro_to_Mill_Footer.adoc[]