= Scala Module Configuration
:page-aliases: Configuring_Mill.adoc

This page goes into more detail about the various configuration options
for `ScalaModule`.

Many of the APIs covered here are listed in the Scaladoc:

* {mill-doc-url}/api/latest/mill/scalalib/ScalaModule.html[mill.scalalib.ScalaModule]


== Compilation & Execution Flags

include::example/scalamodule/1-compilation-execution-flags.adoc[]

== Adding Ivy Dependencies

include::example/scalamodule/2-ivy-deps.adoc[]

== Runtime and Compile-time Dependencies

include::example/scalamodule/3-run-compile-deps.adoc[]

== Test Dependencies

include::example/scalamodule/4-test-deps.adoc[]

== Scala Compiler Plugins

include::example/scalamodule/5-scala-compiler-plugins.adoc[]

== Scaladoc Config

include::example/scalamodule/6-scaladoc.adoc[]

== Unmanaged Jars

include::example/scalamodule/7-unmanaged-jars.adoc[]

== Specifying the Main Class

include::example/scalamodule/8-main-class.adoc[]

== Downloading Non-Maven Jars

include::example/scalamodule/9-downloading-non-maven-jars.adoc[]

== Customizing the Assembly

include::example/scalamodule/10-assembly-config.adoc[]

== Repository Config

include::example/scalamodule/11-repository-config.adoc[]

== Maven Central: Blocked!

Under some circumstances (e.g. corporate firewalls), you may not have access maven central. The typical symptom will be error messages which look like this;

----
1 targets failed
mill.scalalib.ZincWorkerModule.classpath
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi:mill-scalalib-worker_2.13:0.11.1
        not found: C:\Users\partens\.ivy2\local\com.lihaoyi\mill-scalalib-worker_2.13\0.11.1\ivys\ivy.xml
        download error: Caught java.io.IOException (Server returned HTTP response code: 503 for URL: https://repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-worker_2.13/0.11.1/mill-scalalib-worker_2.13-0.11.1.pom) while downloading https://repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-worker_2.13/0.11.1/mill-scalalib-worker_2.13-0.11.1.pom
----

It is expected that basic commands (e.g. clean) will not work, as Mill saying it is unable to resolve it's own, fundamental, dependancies. Under such circumstances, you will normally have access to some proxy, or other corporate repository which resolves maven artefacts. The strategy is simply to tell mill to use that instead.

The idea is to set an environment variable COURSIER_REPOSITORIES (see coursier docs). The below command should set the environment variable for the current shell, and then run the mill command.

----
 COURSIER_REPOSITORIES=https://packages.corp.com/artifactory/maven/ mill resolve _
----

If you are using millw, a more permanent solution could be to set the environment variable at the top of the millw script, or as a user environment variable etc.

== Backticked Names

include::example/scalamodule/12-backticked-names.adoc[]

== Unidoc

include::example/scalamodule/13-unidoc.adoc[]

== Reformatting your code

Mill supports code formatting via https://scalameta.org/scalafmt/[scalafmt] out of the box.

To have a formatting per-module you need to make your module extend `mill.scalalib.scalafmt.ScalafmtModule`:

.`build.sc`
[source,scala,subs="attributes,verbatim"]
----
import mill._, scalalib._, scalafmt._

object foo extends ScalaModule with ScalafmtModule {
  def scalaVersion = "{example-scala-2-13-version}"
}
----

Now you can reformat code with `mill foo.reformat` command, or only check for misformatted files with `mill foo.checkFormat`.

You can also reformat your project's code globally with `+mill mill.scalalib.scalafmt.ScalafmtModule/reformatAll __.sources+` command,
or only check the code's format with `+mill mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources+`.
It will reformat all sources that matches `+__.sources+` query.

If you add a `.scalafmt.conf` file at the root of you project, it will be used
to configure formatting. It can contain a `version` key to specify the scalafmt
version used to format your code. See the
https://scalameta.org/scalafmt/docs/configuration.html[scalafmt configuration documentation]
for details.


== Using the Ammonite Repl / Scala console

All ``ScalaModule``s have a `console` and a `repl` target, to start a Scala console or an Ammonite Repl.

To use the latter, you can (and sometimes need to) customize the Ammonite version to work with your selected Scala version.
Mill provides a default Ammonite version,
but depending on the Scala version you are using, there may be no matching Ammonite release available.
In order to start the repl, you may have to specify a different available Ammonite version.

.Example: Overriding `ammoniteVersion` to select a release compatible to the `scalaVersion`
[source,scala,subs="attributes,verbatim"]
----
import mill._. scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.12.6"
  def ammoniteVersion = "2.4.0"
}
----

[TIP]
--
_Why is Ammonite tied to the exact Scala version?_

This is because Ammonite depends on the Scala compiler.
In contrast to the Scala library, compiler releases do not guarantee any binary compatibility between releases.
As a consequence, Ammonite needs full Scala version specific releases.

The older your used Mill version or the newer the Scala version you want to use, the higher is the risk that the default Ammonite version will not match.
--
