= Scala Build Examples

On this page, we will explore the Mill build tool via a series of simple Scala
example projects. Each project demonstrates one particular feature of the Mill
build tool, and is also an executable codebase you can download and run. By the
end of this page, you will be familiar with how to configure Mill to work with
realistic Scala codebases: cross-building, testing, and publishing them.


Many of the APIs covered here are listed in the Scaladoc:

* {mill-doc-url}/api/latest/mill/scalalib/ScalaModule.html[`mill.scalalib.ScalaModule`]
* {mill-doc-url}/api/latest/mill/main/RootModule.html[`mill.scalalib.RootModule`]
* {mill-doc-url}/api/latest/mill/scalalib/TestModule$.html[`mill.scalalib.TestModule`]
* {mill-doc-url}/api/latest/mill/scalalib/PublishModule.html[`mill.scalalib.PublishModule`]
* {mill-doc-url}/api/latest/mill/scalalib/CrossScalaModule.html[`mill.scalalib.CrossScalaModule`]
* {mill-doc-url}/api/latest/mill/scalalib/SbtModule.html[`mill.scalalib.SbtModule`]
* {mill-doc-url}/api/latest/mill/scalalib/CrossSbtModule.html[`mill.scalalib.CrossSbtModule`]
* {mill-doc-url}/api/latest/mill/scalalib/JavaModule.html[`mill.scalalib.JavaModule`]

== Common Configuration Overrides

include::example/scalabuilds/1-common-config.adoc[]

== Custom Tasks

include::example/scalabuilds/2-custom-tasks.adoc[]

== Overriding Tasks

include::example/scalabuilds/3-override-tasks.adoc[]

== Nesting Modules

include::example/scalabuilds/4-nested-modules.adoc[]

== Scala Module With Test Suite

include::example/scalabuilds/5-test-suite.adoc[]

== Publish Module

include::example/scalabuilds/6-publish-module.adoc[]

== Cross-Scala-Version Modules

include::example/scalabuilds/7-cross-scala-version.adoc[]

== SBT-Compatible Modules

include::example/scalabuilds/8-sbt-compat-modules.adoc[]

== Java Modules

include::example/scalabuilds/9-java-modules.adoc[]

== Realistic Scala Example Project

include::example/scalabuilds/10-scala-realistic.adoc[]


== Example Builds

Mill comes bundled with example builds for existing open-source projects, as
integration tests and examples:

=== Acyclic

include::example/thirdparty/acyclic.adoc[]

=== Fansi

include::example/thirdparty/fansi.adoc[]

=== JimFS

include::example/thirdparty/jimfs.adoc[]
