= Scala Build Examples

On this page, we will explore the Mill build tool via a series of simple Scala
example projects. Each project demonstrates one particular feature of the Mill
build tool, and is also an executable codebase you can download and run. By the
end of this page, you will be familiar with how to configure Mill to work with
realistic Scala codebases: cross-building, testing, and publishing them.


Many of the APIs covered here are listed in the Scaladoc:

* {mill-doc-url}/api/latest/mill/scalalib/ScalaModule.html[mill.scalalib.ScalaModule]
* {mill-doc-url}/api/latest/mill/main/RootModule.html[mill.scalalib.RootModule]
* {mill-doc-url}/api/latest/mill/scalalib/TestModule$.html[mill.scalalib.TestModule]
* {mill-doc-url}/api/latest/mill/scalalib/PublishModule.html[mill.scalalib.PublishModule]
* {mill-doc-url}/api/latest/mill/scalalib/CrossScalaModule.html[mill.scalalib.CrossScalaModule]
* {mill-doc-url}/api/latest/mill/scalalib/SbtModule.html[mill.scalalib.SbtModule]
* {mill-doc-url}/api/latest/mill/scalalib/CrossSbtModule.html[mill.scalalib.CrossSbtModule]
* {mill-doc-url}/api/latest/mill/scalalib/JavaModule.html[mill.scalalib.JavaModule]

include::example/basic/3-common-config.adoc[]

include::example/basic/4-custom-tasks.adoc[]

include::example/basic/5-override-tasks.adoc[]

include::example/basic/6-nested-modules.adoc[]

include::example/basic/7-test-suite.adoc[]

include::example/basic/8-publish-module.adoc[]

include::example/basic/9-cross-scala-version.adoc[]

include::example/basic/10-sbt-compat-modules.adoc[]

include::example/basic/11-java-modules.adoc[]

include::example/basic/12-scala-realistic.adoc[]


== Example Builds

Mill comes bundled with example builds for existing open-source projects, as
integration tests and examples:

=== Acyclic

* {mill-github-url}/blob/main/integration/thirdparty/local/resources/acyclic/build.sc#L1[Mill Build]

A small single-module cross-build, with few sources, minimal dependencies, and
wired up for publishing to Maven Central.

=== Jawn

* {mill-github-url}/blob/main/integration/thirdparty/local/resources/jawn/build.sc#L1[Mill Build]

A collection of relatively small modules, all cross-built across the same few
versions of Scala.

=== Upickle

* {mill-github-url}/blob/main/integration/thirdparty/local/resources/upickle/build.sc#L1[Mill Build]

A single cross-platform Scala.js/Scala-JVM module cross-built against multiple
versions of Scala, including the setup necessary for publishing to Maven Central.

=== Ammonite

* {mill-github-url}/blob/main/integration/thirdparty/local/resources/ammonite/build.sc#L1[Mill Build]

A relatively complex build with numerous submodules, some cross-built across
Scala major versions while others are cross-built against Scala minor versions.

Also demonstrates how to pass one module's compiled artifacts to the
`run`/`test` commands of another, via their `forkEnv`.
