= Tasks

One of Mill's core abstractions is its _Task Graph_: this is how Mill defines,
orders and caches work it needs to do, and exists independently of any support
for building Scala.

Mill target graphs are primarily built using methods and macros defined on
`mill.define.Target`, aliased as `T` for conciseness:

- {mill-doc-url}/api/latest/mill/define/Target$.html[mill.define.Target]

== Task Cheat Sheet

The following table might help you make sense of the small collection of
different Task types:

[cols="<,<,<,<,<,<,<"]
|===
| |Target |Command |Source/Input |Anonymous Task |Persistent Target |Worker

|Cached to Disk |X | | | |X |
|JSON Writable |X |X |X| |X |
|JSON Readable |X | | | |X |
|CLI Runnable |X |X | | |X |
|Takes Arguments | |X | |X | |
|Cached In-Memory | | | | | |X
|===

include::example/depth/tasks/1-task-graph.adoc[]

[#primitive-tasks]
== Primary Tasks

include::example/depth/tasks/2-primary-tasks.adoc[]

== Other Tasks

=== Anonymous Tasks

include::example/depth/tasks/3-anonymous-tasks.adoc[]

=== Inputs

include::example/depth/tasks/4-inputs.adoc[]

=== Persistent Targets

include::example/depth/tasks/5-persistent-targets.adoc[]

=== Workers
include::example/depth/tasks/6-workers.adoc[]


=== Evaluator Commands (experimental)

_Evaluator Command are experimental and suspected to change.
See {mill-github-url}/issues/502[issue #502] for details._

You can define a command that takes in the current `Evaluator` as an argument,
which you can use to inspect the entire build, or run arbitrary tasks.
For example, here is the `mill.scalalib.GenIdea/idea` command which uses this
to traverse the module-tree and generate an Intellij project config for your
build.

[source,scala]
----
def idea(ev: Evaluator) = T.command {
  mill.scalalib.GenIdea(
    implicitly,
    ev.rootModule,
    ev.discover
  )
}
----

Many built-in tools are implemented as custom evaluator commands:
xref:Scala_Builtin_Commands.adoc#_inspect[inspect],
xref:Scala_Builtin_Commands.adoc#_resolve[resolve],
xref:Scala_Builtin_Commands.adoc#_show[show].
If you want a way to run Mill commands and programmatically manipulate the
tasks and outputs, you do so with your own evaluator command.

=== Using ScalaModule.run as a task

include::example/depth/tasks/11-module-run-task.adoc[]
