addSbtPlugin("com.eed3si9n"       % "sbt-doge"        % "0.1.5")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.2.25")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "0.1.14")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "1.0.1")
addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.5")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "1.1")
