= Scripting on the JVM with Java, Kotlin, and Scala
// tag::header[]
:author: Li Haoyi
:revdate: 24 September 2025

_{author}, {revdate}_


This article will explore use of JVM languages as scripting languages, replacing the Bash and
Python scripts common throughout the industry. We will walk through examples of how the JVM's
benefits of performance, compile-time safety, and vast library ecosystem are advantages over
traditional script platforms, but also how language verbosity, build tool overhead, and lack
of convenient libraries hampers the effort. Lastly we will demonstrate how script-focused
tooling is able to smooth over some of those issues, simplifying build configuration and
providing suitable libraries to make the JVM truly a world-class scripting environment as robust
as any scripting language out there.

// end::header[]

== Challenges of Small-Scale Java Programs

- Hard to install Java+Maven/Gradle
- Configuring Maven/Gradle for a small script is tedious and annoying
- Very verbose language for small scripts

== Lightweight Build Tools

- Mill is super easy to install
- Very easy to configure for small projects and scripts
- Still very verbose writing small scripts

== Lightweight Languages

- Kotlin is much more syntactically concise than Java
- Much less code to write the same things overall

== Lightweight Libraries

- OS-Lib, Requests-Scala, MainArgs

== Vertical Integration

- Integration between Mill Scala Scripts and Mainargs makes it even cleaner

== Future Work

- Top-level statements
- Collection & Data Structure Literals