= Common Project Layouts

Earlier, we have shown how to work with the Mill default Scala module layout.
Here we will explore some other common project layouts that you may want in your
Scala build:

include::example/basic/3-common-config.adoc[]

include::example/basic/4-custom-tasks.adoc[]

include::example/basic/5-nested-modules.adoc[]

include::example/basic/6-test-suite.adoc[]

include::example/basic/7-publish-module.adoc[]

include::example/basic/8-cross-scala-version.adoc[]

include::example/basic/9-sbt-compatible-modules.adoc[]

include::example/basic/10-java-modules.adoc[]

include::example/basic/11-scala-realistic.adoc[]


== Example Builds

Mill comes bundled with example builds for existing open-source projects, as
integration tests and examples:

=== Acyclic

* {mill-github-url}/blob/main/integration/thirdparty/local/resources/acyclic/build.sc#L1[Mill Build]

A small single-module cross-build, with few sources, minimal dependencies, and
wired up for publishing to Maven Central.

=== Jawn

* {mill-github-url}/blob/main/integration/thirdparty/local/resources/jawn/build.sc#L1[Mill Build]

A collection of relatively small modules, all cross-built across the same few
versions of Scala.

=== Upickle

* {mill-github-url}/blob/main/integration/thirdparty/local/resources/upickle/build.sc#L1[Mill Build]

A single cross-platform Scala.js/Scala-JVM module cross-built against multiple
versions of Scala, including the setup necessary for publishing to Maven Central.

=== Ammonite

* {mill-github-url}/blob/main/integration/thirdparty/local/resources/ammonite/build.sc#L1[Mill Build]

A relatively complex build with numerous submodules, some cross-built across
Scala major versions while others are cross-built against Scala minor versions.

Also demonstrates how to pass one module's compiled artifacts to the
`run`/`test` commands of another, via their `forkEnv`.
