package mill.meta

import scala.jdk.CollectionConverters.CollectionHasAsScala
import mill.constants.CodeGenConstants as CGConst
import mill.api.Result
import mill.internal.Util.backtickWrap
import pprint.Util.literalize
import mill.api.daemon.internal.MillScalaParser
import mill.api.internal.HeaderData
import mill.api.daemon.Segment

import scala.util.control.Breaks.*

object CodeGen {

  val generatedFileHeader =
    s"// Generated by Mill ${mill.meta.BuildInfo.millRunnerMetaVersion}"

  def generateWrappedAndSupportSources(
      projectRoot: os.Path,
      allScriptCode: Map[os.Path, String],
      wrappedDest: os.Path,
      supportDest: os.Path,
      resourceDest: os.Path,
      millTopLevelProjectRoot: os.Path,
      output: os.Path,
      parser: MillScalaParser
  ): Unit = {
    val scriptSources = allScriptCode.keys.toSeq.sorted

    for (scriptPath <- scriptSources) {
      val scriptFolderPath = scriptPath / os.up
      val packageSegments = FileImportGraph.fileImportToSegments(projectRoot, scriptPath)
      val wrappedDestFile = wrappedDest / packageSegments
      val pkgSegments = packageSegments.drop(1).dropRight(1)
      def pkgSelector0(pre: Option[String], s: Option[String]) =
        (pre ++ pkgSegments ++ s).map(backtickWrap).mkString(".")

      val pkg = pkgSelector0(Some(CGConst.globalPackagePrefix), None)

      val segments = calcSegments(scriptFolderPath, projectRoot)
      val supportDestDir = supportDest / packageSegments / os.up

      val childNames = scriptSources
        .collect {
          case path
              if path != scriptPath
                && CGConst.nestedBuildFileNames.contains(path.last)
                && path / os.up / os.up == scriptFolderPath => (path / os.up).last
        }
        .distinct

      def pkgSelector2(s: Option[String]) =
        s"_root_.${pkgSelector0(Some(CGConst.globalPackagePrefix), s)}"

      val childAliases = childNames
        .map { c =>
          // Dummy references to sub-modules. Just used as metadata for the discover and
          // resolve logic to traverse, cannot actually be evaluated and used
          val lhs = backtickWrap(c + "_alias")
          val rhs = s"${pkgSelector2(Some(c))}.`package`"
          s"final lazy val $lhs: $rhs.type = $rhs // subfolder module reference"
        }
        .mkString("\n  ")

      if (scriptFolderPath == projectRoot) {
        val buildFileImplCode = generateBuildFileImpl(pkg)
        os.write.over(
          supportDestDir / "BuildFileImpl.scala",
          buildFileImplCode,
          createFolders = true
        )
      }

      val miscInfo = generateMillMiscInfo(
        pkg = pkg,
        scriptFolderPath = scriptFolderPath,
        segments = segments,
        millTopLevelProjectRoot = millTopLevelProjectRoot,
        output = output
      )

      if (scriptPath.last.endsWith(".yaml")) {
        val newParent =
          if (segments.isEmpty) "_root_.mill.util.MainRootModule"
          else "_root_.mill.api.internal.SubfolderModule(build.millDiscover)"
        val parsedHeaderData = mill.internal.Util.parseHeaderData(scriptPath).get

        val prelude =
          s"""|import MillMiscInfo._
              |import _root_.mill.util.TokenReaders.given
              |import _root_.mill.runner.autooverride.AutoOverride
              |""".stripMargin

        def processDataRest[T](data: HeaderData)(
            onProperty: (String, upickle.core.BufferedValue) => T,
            onNestedObject: (String, HeaderData) => T
        ): Seq[T] = {
          for ((locatedKeyString, v) <- data.rest.toSeq)
            yield locatedKeyString.value.split(" +") match {
              case Array(k) => onProperty(k, v)
              case Array("object", k) => onNestedObject(
                  k,
                  upickle.core.BufferedValue.transform(
                    v,
                    HeaderData.headerDataReader(scriptPath)
                  )
                )
              case _ => throw new Result.Exception(
                  "",
                  Some(Result.Failure(
                    "Invalid key: " + locatedKeyString.value,
                    scriptPath.toNIO,
                    locatedKeyString.index
                  ))
                )
            }
        }

        val miscInfoWithResource = {
          val header = if (pkg.isBlank()) "" else s"package $pkg"
          val miscInfoBody = if (segments.isEmpty) {
            rootMiscInfo(scriptFolderPath, millTopLevelProjectRoot, output)
          } else {
            subfolderMiscInfo(scriptFolderPath, segments)
          }
          s"""|$generatedFileHeader
              |$header
              |
              |$miscInfoBody
              |""".stripMargin
        }
        os.write.over(
          supportDestDir / "MillMiscInfo.scala",
          miscInfoWithResource,
          createFolders = true
        )

        def renderTemplate(prefix: String, data: HeaderData, path: Seq[String]): String = {
          val extendsConfig = data.`extends`.value.map(_.value)
          val definitions = processDataRest(data)(
            onProperty = (_, _) => "", // Properties will be auto-implemented by AutoOverride
            onNestedObject = (k, nestedData) =>
              renderTemplate(s"object $k", nestedData, path :+ k)
          ).filter(_.nonEmpty)

          def parseRender(moduleDep: String) = {
            mill.resolve.ParseArgs.extractSegments(moduleDep) match {
              case f: Result.Failure =>
                sys.error("Unable to parse module dep " + literalize(moduleDep) + ": " + f.error)
              case Result.Success((rootModulePrefix, taskSegments)) =>
                val renderedSegments = taskSegments.value
                  .map {
                    case Segment.Label(s) => backtickWrap(s)
                    case Segment.Cross(vs) => "lookup(" + vs.map(literalize(_)).mkString(", ") + ")"
                  }
                  .mkString(".")

                rootModulePrefix match {
                  case "" => s"build.$renderedSegments"
                  case s"$externalModulePrefix/" => s"$externalModulePrefix.$renderedSegments"
                }
            }
          }

          val moduleDepsSnippet =
            if (data.moduleDeps.value.isEmpty) ""
            else
              s"override def moduleDeps = Seq(${data.moduleDeps.value.map(_.value).map(parseRender).mkString(", ")})"

          val compileModuleDepsSnippet =
            if (data.compileModuleDeps.value.isEmpty) ""
            else
              s"override def compileModuleDeps = Seq(${data.compileModuleDeps.value.map(_.value).map(parseRender).mkString(", ")})"

          val runModuleDepsSnippet =
            if (data.runModuleDeps.value.isEmpty) ""
            else
              s"override def runModuleDeps = Seq(${data.runModuleDeps.value.map(_.value).map(parseRender).mkString(", ")})"

          val extendsSnippet =
            if (extendsConfig.nonEmpty)
              s" extends ${extendsConfig.mkString(", ")}, AutoOverride[_root_.mill.T[?]]"
            else " extends AutoOverride[_root_.mill.T[?]]"

          val allSnippets = Seq(
            moduleDepsSnippet,
            compileModuleDepsSnippet,
            runModuleDepsSnippet,
            "inline def autoOverrideImpl[T](): T = ${ mill.api.Task.notImplementedImpl[T] }"
          ).filter(_.nonEmpty) ++ definitions

          s"""$prefix$extendsSnippet {
             |  ${allSnippets.mkString("\n  ")}
             |}
             |""".stripMargin
        }

        os.write.over(
          (wrappedDestFile / os.up) / wrappedDestFile.baseName,
          s"""package $pkg
             |import mill.*, scalalib.*, javalib.*, kotlinlib.*
             |$prelude
             |//SOURCECODE_ORIGINAL_FILE_PATH=$scriptPath
             |@scala.annotation.experimental object `package` extends $newParent, PackageTrait {
             |  ${if (segments.isEmpty) millDiscover(segments.nonEmpty) else ""}
             |  $childAliases
             |}
             |${renderTemplate("trait PackageTrait", parsedHeaderData, segments)}
             |""".stripMargin,
          createFolders = true
        )

      } else {
        breakable {
          val specialNames =
            (CGConst.nestedBuildFileNames.asScala ++ CGConst.rootBuildFileNames.asScala).toSet

          val isBuildScript = specialNames(scriptPath.last)

          val scriptName = scriptPath.last

          if (
            scriptFolderPath == projectRoot
            && CGConst.nestedBuildFileNames.contains(scriptName)
          ) break()
          if (
            scriptFolderPath != projectRoot
            && CGConst.rootBuildFileNames.contains(scriptName)
          ) break()

          val scriptCode = allScriptCode(scriptPath)

          val markerComment =
            s"""//SOURCECODE_ORIGINAL_FILE_PATH=$scriptPath
               |//SOURCECODE_ORIGINAL_CODE_START_MARKER""".stripMargin

          val siblingScripts = scriptSources
            .filter(_ != scriptPath)
            .filter(p => (p / os.up) == (scriptPath / os.up))
            .map(_.last.split('.').head + "_")

          val importSiblingScripts = siblingScripts
            .filter(s => s != "build_" && s != "package_")
            .map(s => s"import $pkg.${backtickWrap(s)}.*").mkString("\n")

          if (isBuildScript) {
            os.write.over(supportDestDir / "MillMiscInfo.scala", miscInfo, createFolders = true)
          }

          val parts =
            if (!isBuildScript) {
              val wrapperName = backtickWrap(scriptPath.last.split('.').head + "_")
              s"""|$generatedFileHeader
                  |package $pkg
                  |
                  |$importSiblingScripts
                  |
                  |object $wrapperName {
                  |$markerComment
                  |$scriptCode
                  |}
                  |
                  |export $wrapperName._
                  |""".stripMargin
            } else {
              generateBuildScript(
                projectRoot = projectRoot,
                millTopLevelProjectRoot = millTopLevelProjectRoot,
                scriptPath = scriptPath,
                scriptFolderPath = scriptFolderPath,
                childAliases = childAliases,
                pkg = pkg,
                scriptCode = scriptCode,
                markerComment = markerComment,
                parser = parser,
                siblingScripts = siblingScripts,
                importSiblingScripts = importSiblingScripts
              )
            }

          os.write(wrappedDestFile, parts, createFolders = true)
        }
      }
    }
  }

  private def calcSegments(scriptFolderPath: os.Path, projectRoot: os.Path) =
    scriptFolderPath.relativeTo(projectRoot).segments

  private def generateMillMiscInfo(
      pkg: String,
      scriptFolderPath: os.Path,
      segments: Seq[String],
      millTopLevelProjectRoot: os.Path,
      output: os.Path
  ): String = {
    val header = if (pkg.isBlank()) "" else s"package $pkg"
    val body =
      if (segments.nonEmpty) subfolderMiscInfo(scriptFolderPath, segments)
      else rootMiscInfo(
        scriptFolderPath,
        millTopLevelProjectRoot,
        output
      )

    s"""|$generatedFileHeader
        |$header
        |
        |$body
        |""".stripMargin
  }

  def generateBuildFileImpl(pkg: String) = {
    s"""|$generatedFileHeader
        |package $pkg
        |
        |object BuildFileImpl extends mill.api.internal.BuildFileCls(`package`)
        |""".stripMargin
  }

  private def generateBuildScript(
      projectRoot: os.Path,
      millTopLevelProjectRoot: os.Path,
      scriptPath: os.Path,
      scriptFolderPath: os.Path,
      childAliases: String,
      pkg: String,
      scriptCode: String,
      markerComment: String,
      parser: MillScalaParser,
      siblingScripts: Seq[String],
      importSiblingScripts: String
  ): String = {
    val segments = calcSegments(scriptFolderPath, projectRoot)

    val exportSiblingScripts =
      siblingScripts.map(s => s"export $pkg.${backtickWrap(s)}.*").mkString("\n")

    val prelude =
      s"""|import MillMiscInfo._
          |import _root_.mill.util.TokenReaders.given
          |import _root_.mill.api.JsonFormatters.given
          |""".stripMargin

    val objectData = parser.parseObjectData(scriptCode)

    val expectedModuleMsg =
      if (projectRoot != millTopLevelProjectRoot) "MillBuildRootModule" else "mill.Module"

    val pkgLine = s"package $pkg"

    val newParent =
      if (segments.isEmpty) "_root_.mill.util.MainRootModule"
      else "_root_.mill.api.internal.SubfolderModule(build.millDiscover)"

    val parentClause = s"$newParent with MillDiscoverWrapper"

    val millDiscoverWrapper =
      s"""|trait MillDiscoverWrapper { this: `package`.type =>
          |  ${millDiscover(segments.nonEmpty)}
          |  $childAliases
          |  ${exportSiblingScripts.linesWithSeparators.mkString("  ")}
          |}
          |""".stripMargin

    objectData.find(o => o.name.text == "`package`") match {
      case Some(objectData) =>

        var newScriptCode = scriptCode

        newScriptCode = objectData.parent.applyTo(
          newScriptCode,
          if (objectData.parent.text == null) {
            throw new Result.Exception(
              s"object `package` in ${scriptPath.relativeTo(millTopLevelProjectRoot)} " +
                s"must extend a subclass of `$expectedModuleMsg`"
            )
          } else {
            // `extends` clauses can have the parent followed by either `with` or `,`
            // separators, but it needs to be consistent. So we need to try and see if
            // any separators are already present and if so follow suite. Not 100%
            // precise, but probably works well enough people will rarely hit issues
            val postParent = newScriptCode.drop(objectData.parent.end).trim
            val sep = {
              if (postParent.startsWith(",")) ", "
              else if (postParent.startsWith("with")) " with "
              else " with " // no separator found, use `with` to be consistent with MillDiscoverWrapper
            }

            newParent + sep + objectData.parent.text + " with MillDiscoverWrapper"
          }
        )

        newScriptCode = objectData.obj.applyTo(newScriptCode, "@scala.annotation.experimental object")

        s"""$generatedFileHeader
           |$pkgLine
           |
           |$importSiblingScripts
           |$prelude
           |$markerComment
           |$newScriptCode
           |
           |$millDiscoverWrapper
           |""".stripMargin

      case None =>
        s"""$generatedFileHeader
           |$pkgLine
           |
           |$importSiblingScripts
           |$prelude
           |@scala.annotation.experimental object `package` extends $parentClause {
           |$markerComment
           |$scriptCode
           |}
           |
           |$millDiscoverWrapper
           |""".stripMargin

    }
  }

  def subfolderMiscInfo(
      scriptFolderPath: os.Path,
      segments: Seq[String]
  ): String = {
    s"""|object MillMiscInfo
        |    extends mill.api.internal.SubfolderModule.Info(
        |  millSourcePath0 = os.Path(${literalize(scriptFolderPath.toString)}),
        |  segments = _root_.scala.Seq(${segments.map(literalize(_)).mkString(", ")})
        |)
        |""".stripMargin
  }

  def millDiscover(segmentsNonEmpty: Boolean): String = {
    if (segmentsNonEmpty) ""
    else {
      val rhs = "_root_.mill.api.Discover[`package`.type]"
      s"override lazy val millDiscover: _root_.mill.api.Discover = $rhs"
    }
  }

  def rootMiscInfo(
      scriptFolderPath: os.Path,
      millTopLevelProjectRoot: os.Path,
      output: os.Path
  ): String = {
    s"""|@_root_.scala.annotation.nowarn
        |object MillMiscInfo
        |    extends mill.api.internal.RootModule.Info(
        |  projectRoot0 = ${literalize(scriptFolderPath.toString)},
        |  output0 = ${literalize(output.toString)},
        |  topLevelProjectRoot0 = ${literalize(millTopLevelProjectRoot.toString)}
        |)
        |""".stripMargin
  }

}
