package mill.util.internal

import mill.api.{BuildCtx, Discover, DynamicModule, Module}
import mill.api.daemon.Result
import mill.api.internal.{HeaderData, Located, PrecompiledModuleRef}
import mill.util.MainRootModule
import mill.util.TokenReaders.given

/**
 * Root module fallback used when codegen produces no `build_.package_`, e.g.
 * when the workspace has no `build.mill`/`build.mill.yaml`, or when the root
 * `build.mill.yaml` itself is a precompiled module
 * (`mill-experimental-precompiled-module: true`).
 *
 * Walks the workspace for top-level `*.mill.yaml` files marked as precompiled
 * and exposes them as direct children, so `BuildCtx.rootModule.moduleInternal.modules`
 * enumerates them and `mill resolve __` can discover them.
 *
 * Discovery is eager: every top-level precompiled YAML module is instantiated
 * when `moduleDirectChildren` is first touched, so by the time any module's
 * `moduleDeps` runs, the full sibling set is present in
 * `PrecompiledModuleRef.cache`.
 */
private[mill] object PrecompiledDiscoveryRootModule extends MainRootModule with DynamicModule {
  override lazy val millDiscover: Discover = Discover[this.type]

  private lazy val precompiledChildren: Seq[Module] = BuildCtx.withFilesystemCheckerDisabled {
    val ws = BuildCtx.workspaceRoot

    // (subdir name, yaml path) for every immediate subdirectory containing a
    // top-level precompiled YAML module. Sorted by directory name so the order
    // of children is deterministic across runs.
    val candidates: Seq[(String, os.Path)] =
      if (!os.isDir(ws)) Nil
      else os.list(ws)
        .filter(os.isDir)
        .sortBy(_.last)
        .flatMap { dir =>
          Seq("package.mill.yaml", "build.mill.yaml").iterator
            .map(dir / _)
            .find(p => os.isFile(p) && isPrecompiledYaml(p))
            .map(p => (dir.last, p))
        }

    // Map from the first segment of a `moduleDeps:` reference (e.g. "foo" in
    // "foo.test") to its YAML path, so cross-sibling deps can resolve without
    // going through the reflective `PrecompiledModuleRef.resolveModuleRef`
    // (which expects a parent with named methods generated by codegen).
    val yamlByName: Map[String, os.Path] = candidates.toMap

    def instantiate(yamlPath: os.Path): Module = {
      val relPath = yamlPath.relativeTo(ws).toString
      val header = headerOf(yamlPath)
      val extendsClass = header.`extends`.value.value.headOption.map(_.value).getOrElse {
        val msg = s"Precompiled YAML $relPath has no `extends:` clause"
        throw new mill.api.daemon.Result.Exception(
          msg,
          Some(mill.api.daemon.Result.Failure(msg, yamlPath.toNIO, 0))
        )
      }

      def resolveSibling(ref: String): Option[Module] =
        yamlByName.get(ref.split('.').head).map(instantiate)

      def depsMap(get: HeaderData.NestedModuleDeps => Seq[Located[String]])
          : Map[String, Seq[Module]] =
        HeaderData.collectAllNestedDeps(yamlPath, header, "")
          .flatMap { entry =>
            val resolved = get(entry).flatMap(loc => resolveSibling(loc.value))
            if (resolved.isEmpty) None else Some(entry.key -> resolved)
          }.toMap

      PrecompiledModuleRef(
        this,
        relPath,
        extendsClass,
        () => depsMap(_.moduleDeps),
        () => depsMap(_.compileModuleDeps),
        () => depsMap(_.runModuleDeps),
        () => depsMap(_.bomModuleDeps)
      )
    }

    candidates.map { case (_, yamlPath) => instantiate(yamlPath) }
  }

  private def isPrecompiledYaml(path: os.Path): Boolean =
    headerOf(path).`mill-experimental-precompiled-module`.value

  private def headerOf(path: os.Path): HeaderData =
    PrecompiledModuleRef.headerDataParser(path) match {
      case Result.Success(hd) => hd
      case _ => HeaderData(rest = Map.empty)
    }

  override def moduleDirectChildren: Seq[Module] =
    super.moduleDirectChildren ++ precompiledChildren
}
