= Java Packaging & Publishing
:page-aliases: Publishing_Java_Projects.adoc

include::partial$gtag-config.adoc[]

This page will discuss common topics around packaging and publishing your Java projects for others to use

== Customizing the Assembly

include::partial$example/javalib/publishing/1-assembly-config.adoc[]



== Publishing Locally

include::partial$example/javalib/publishing/2-publish-module.adoc[]

== Checking API compatibility

Mill provides the ability to check API changes with the https://revapi.org/revapi-site/main/index.html[Revapi] analysis and change tracking tool.

include::partial$example/javalib/publishing/3-revapi.adoc[]

CAUTION: The `revapi` task does not fail if incompatibilities are reported. You should fix these, and verify by re-running `revapi`, before a release.

[TIP]
====
The `revapi` task returns the path to a directory that can be used to resolve the relative path to any extension configuration output.
[source,json]
----
[
  {
    "extension": "revapi.reporter.text",
    "configuration": {
      "minSeverity": "BREAKING",
      "output": "report.txt"
    }
  }
]
----
====

include::partial$Publishing_Footer.adoc[]

== Java App and Bundles using `jlink`

include::partial$example/javalib/publishing/5-jlink.adoc[]

== Java Installers using `jpackage`

include::partial$example/javalib/publishing/6-jpackage.adoc[]


== Building Native Image with Graal VM

include::partial$example/javalib/publishing/7-native-image.adoc[]


For another example building a slightly less trivial project into a Graal native
image, see below:

include::partial$example/javalib/publishing/8-native-image-config.adoc[]

