= Scala Build Examples
:page-aliases: Scala_Build_Examples.adoc

++++
<script>
gtag('config', 'AW-16649289906');
</script>
++++

On this page, we will explore the Mill build tool via a series of simple Scala
example projects. Each project demonstrates one particular feature of the Mill
build tool, and is also an executable codebase you can download and run. By the
end of this page, you will be familiar with how to configure Mill to work with
realistic Scala codebases: cross-building, testing, and publishing them.


Many of the APIs covered here are listed in the Scaladoc:

* {mill-doc-url}/api/latest/mill/scalalib/ScalaModule.html[`mill.scalalib.ScalaModule`]
* {mill-doc-url}/api/latest/mill/main/RootModule.html[`mill.scalalib.RootModule`]
* {mill-doc-url}/api/latest/mill/scalalib/TestModule$.html[`mill.scalalib.TestModule`]
* {mill-doc-url}/api/latest/mill/scalalib/PublishModule.html[`mill.scalalib.PublishModule`]
* {mill-doc-url}/api/latest/mill/scalalib/CrossScalaModule.html[`mill.scalalib.CrossScalaModule`]
* {mill-doc-url}/api/latest/mill/scalalib/SbtModule.html[`mill.scalalib.SbtModule`]
* {mill-doc-url}/api/latest/mill/scalalib/CrossSbtModule.html[`mill.scalalib.CrossSbtModule`]
* {mill-doc-url}/api/latest/mill/scalalib/JavaModule.html[`mill.scalalib.JavaModule`]

== Nesting Modules

include::partial$example/scalalib/builds/1-nested-modules.adoc[]


== SBT-Compatible Modules

include::partial$example/scalalib/builds/2-compat-modules.adoc[]


== Cross-Scala-Version Modules

include::partial$example/scalalib/builds/3-cross-scala-version.adoc[]


== Realistic Scala Example Project

include::partial$example/scalalib/builds/4-realistic.adoc[]


== Example Builds for Real Projects

Mill comes bundled with example builds for real-world open-source projects,
demonstrating how Mill can be used to build code outside of tiny example codebases:

=== Acyclic

include::partial$example/thirdparty/acyclic.adoc[]

=== Fansi

include::partial$example/thirdparty/fansi.adoc[]

== Real World Mill Builds

=== Ammonite

https://github.com/com-lihaoyi/Ammonite[Ammonite] is an ergonomic Scala REPL.

=== Scala-CLI

https://github.com/VirtusLab/scala-cli[Scala-CLI] is the primary CLI tool that
runs when you enter `scala` in the terminal. It is able to compile, test, run,
and package your Scala code in a variety of different ways

=== Coursier

https://github.com/coursier/coursier[Coursier] is a fast JVM dependency resolver,
used in many build tools down resolve and download third party dependencies