== Instructions for Publishing to Sonatype Maven Central

Once you've mixed in `PublishModule`, apart from publishing locally, you can also publish
your project's modules to maven central

=== GPG

If you've never created a keypair before that can be used to sign your artifacts
you'll need to do this. https://central.sonatype.org/publish/requirements/gpg/[Sonatype's GPG Documentation]
has the instructions on how to do this

=== Publishing Secrets

Mill uses the following environment variables as a way to pass the necessary secrets
for publishing:


[source,sh]
----
# The LHS and RHS of the User Token, accessible through the sonatype
# website `Profile` / `User Token` / `Access User Token`
export MILL_SONATYPE_USERNAME=...
export MILL_SONATYPE_PASSWORD=...

# The base-64 encoded PGP key, which can be encoded in the following way
# for each OS:
#
# MacOS or FreeBSD
# gpg --export-secret-key -a $LONG_ID | base64
#
# Ubuntu (assuming GNU base64)
# gpg --export-secret-key -a $LONG_ID | base64 -w0
#
# Arch
# gpg --export-secret-key -a $LONG_ID | base64 | sed -z 's;\n;;g'
#
# Windows
# gpg --export-secret-key -a %LONG_ID% | openssl base64
export MILL_PGP_SECRET_BASE64=...

# The passphrase associated with your PGP key
export MILL_PGP_PASSPHRASE=...
----

Sonatype Maven Central needs your public key to be uploaded so it can use to verify your artifacts.


[source.sh]
----
# Send your public key to ubuntu server so Sonatype Maven Central can use for verification of the artifacts
gpg --keyserver  keyserver.ubuntu.com --send-keys longIDHere

# Check the server for information about the public key. information will be displayed if found
gpg --keyserver  keyserver.ubuntu.com --recv-keys longIDHere
----

=== Publishing

You can publish all eligible modules in your Mill project using
the xref:fundamentals/modules.adoc#_default_tasks[default task] of the
xref:fundamentals/modules.adoc#_external_modules[External Module] `mill.scalalib.PublishModule`:

[source,console]
----
> mill mill.scalalib.PublishModule/
----

You can also specify individual modules you want to publish via a selector:

[source,console]
----
> mill mill.scalalib.PublishModule/ --publishArtifacts foo.publishArtifacts
----

The default URL for publishing to sonatype's Maven Central is `oss.sonatype.org`.
Newer projects registered on sonatype may need to publish using `s01.oss.sonatype.org`.
In that case, you can pass in a `--sonatypeUri`:

[source,console]
----
> mill mill.scalalib.PublishModule/ \
        --sonatypeUri https://s01.oss.sonatype.org/service/local
----

This also allows you to publish to your own internal corporate sonatype deployment,
by passing in `--sonatypeUri example.company.com` instead.

[NOTE]
--
Since Feb. 2021 any new Sonatype accounts have been created on
`s01.oss.sonatype.org`, so you'll want to ensure you set the relevant URIs to match.

The symptom of using the "wrong" URL for publishing is typically a 403 error code, in response to the publish request.

See https://central.sonatype.org/publish/publish-guide/#releasing-to-central

Typically

* `https://s01.oss.sonatype.org/service/local` - for the `--sonatypeUri`
* `https://s01.oss.sonatype.org/content/repositories/snapshots` - for `sonatypeSnapshotUri`

--
=== Publishing Using Github Actions


To publish on Github Actions, you can use something like this:

```yaml
# .github/workflows/publish-artifacts.yml
name: Publish Artifacts
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./mill mill.scalalib.PublishModule/
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
```

Where `MILL_PGP_PASSPHRASE`, `MILL_PGP_SECRET_BASE64`, `MILL_SONATYPE_PASSWORD`, and
`MILL_SONATYPE_USERNAME` configured for the repository's or organization's Github Actions
workflows. See
https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions[Using Secrets in Github Actions]
for more details.

=== Non-Staging Releases (classic Maven uploads)

If the site does not support staging releases as `oss.sonatype.org` and `s01.oss.sonatype.org` do (for
example, a self-hosted OSS nexus site), you can pass in the
`--stagingRelease false` option to simply upload release artifacts to corresponding
maven path under `sonatypeUri` instead of staging path.

[source,console]
----
> mill mill.scalalib.PublishModule/ \
        --publishArtifacts foo.publishArtifacts \
        --sonatypeCreds lihaoyi:$SONATYPE_PASSWORD \
        --sonatypeUri http://example.company.com/release \
        --stagingRelease false
----


== Publishing to other repositories

While Sonatype Maven Central is the default publish repository for JVM ecosystem projects,
there are also others that you can use. Mill supports these largely through contrib plugins:

* xref:contrib/codeartifact.adoc[]
* xref:contrib/artifactory.adoc[]
* xref:contrib/bintray.adoc[]
