== Publishing to Maven Central

Once you've mixed in `PublishModule`, apart from publishing locally, you can also publish
your project's modules to maven central

=== GPG

If you've never created a keypair before that can be used to sign your artifacts
you'll need to do this. https://central.sonatype.org/publish/requirements/gpg/[Sonatype's GPG Documentation]
has the instructions on how to do this

=== Publishing Secrets

Mill uses the following environment variables as a way to pass the necessary secrets
for publishing to Maven Central:


[,sh]
----
# Sonatype Central Portal needs your public key to be uploaded so it can use for verification of artifacts from their end.
#
# Send your public key to ubuntu server so Sonatype Maven Central can use for verification of the artifacts
gpg --keyserver  keyserver.ubuntu.com --send-keys $LONG_ID
#
# Check the server for information about the public key. information will be displayed if found
gpg --keyserver  keyserver.ubuntu.com --recv-keys $LONG_ID
#
# The LHS and RHS of the User Token, accessible through the sonatype
# website `Profile` / `User Token` / `Access User Token`
export MILL_SONATYPE_USERNAME=...
export MILL_SONATYPE_PASSWORD=...

# The base-64 encoded PGP key, which can be encoded in the following way
# for each OS:
#
# MacOS or FreeBSD
# gpg --export-secret-key -a $LONG_ID | base64
#
# Ubuntu (assuming GNU base64)
# gpg --export-secret-key -a $LONG_ID | base64 -w0
#
# Arch
# gpg --export-secret-key -a $LONG_ID | base64 | sed -z 's;\n;;g'
#
# Windows
# gpg --export-secret-key -a %LONG_ID% | openssl base64
export MILL_PGP_SECRET_BASE64=...

# The passphrase associated with your PGP key
export MILL_PGP_PASSPHRASE=...
----

=== Publishing

You can publish all eligible modules in your Mill project using 
`mill.javalib.SonatypeCentralPublishModule/`:

[,console]
----
> mill mill.javalib.SonatypeCentralPublishModule/
----

You can also specify individual modules you want to publish in two ways:

[source,console]
----
> mill foo.publishSonatypeCentral
----

[,console]
----
> mill mill.javalib.SonatypeCentralPublishModule/ --publishArtifacts foo.publishArtifacts
----

=== SNAPSHOT versions

To publish SNAPSHOT versions (that is any version that ends with `-SNAPSHOT`), you need to enable support for them in
your Sonatype Central namespace. To do that, go to the
https://central.sonatype.com/publishing/namespaces[Sonatype Central portal], click on the "three dots" next to the
namespace name, and click on "Enable SNAPSHOTs".

SNAPSHOT versions do not have same semantics as regular versions: they are not signed and are not kept forever in the
repository.

See https://central.sonatype.org/publish/publish-portal-snapshots/[Sonatype Central documentation] for more information.

Your build file should look like:

[source,yaml]
----
extends: JavaModule
publishVersion: 0.0.1-SNAPSHOT
----

Running any of the publishing tasks will now publish SNAPSHOT versions. When running them you should see a note from
Mill that it has detected a SNAPSHOT version.

To consume SNAPSHOT versions in your project, make sure to add the snapshot repository to your build file:

[source,yaml]
----
extends: JavaModule
repositories: ["https://central.sonatype.com/repository/maven-snapshots"]
mvnDeps:
- com.example:mymodule:1.0.0-SNAPSHOT
----

=== Publishing Using Github Actions

To publish on Github Actions, you can use something like this:

[,yaml]
----
# .github/workflows/publish-artifacts.yml
name: Publish Artifacts
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./mill mill.javalib.SonatypeCentralPublishModule/
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
----

Where `MILL_PGP_PASSPHRASE`, `MILL_PGP_SECRET_BASE64`, `MILL_SONATYPE_PASSWORD`, and
`MILL_SONATYPE_USERNAME` configured for the repository's or organization's Github Actions
workflows. See
https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions[Using Secrets in Github Actions]
for more details.

This will set up a Github Actions workflow that will be run automatically when any tag is pushed,
and can also be run manually. If you set up xref:#_versioning_based_on_git_tags[Versioning Based
on Git Tags], then the `publishVersion` will be configured to the git tag version (e.g. `1.1.0`)
for tagged versions, and a longer `0.1.0-<commits-since-last-tag>-<commit-sha>` version
(e.g. `1.1.0-10-fec938`) if manually publishing un-tagged released.

== Publishing to Generic Maven Repositories

Apart from publishing your project's modules to Maven Central, you may also want to publish them to a generic
Maven repository (such as a privately hosted one).

=== Publishing Secrets

Mill uses the following environment variables as a way to pass the necessary secrets for publishing:

[,sh]
----
# Credentials for publishing to the repository
export MILL_MAVEN_USERNAME=...
export MILL_MAVEN_PASSWORD=...
----

=== Publishing

You can publish all eligible modules in your Mill project using the
xref:fundamentals/modules.adoc#_default_tasks[Default Task] of the
xref:fundamentals/modules.adoc#_external_modules[External Module] `mill.javalib.MavenPublishModule`: 

[source,console]
----
> mill mill.javalib.MavenPublishModule/ \
        --username myusername \
        --password mypassword \
        --releaseUri https://example.company.com/release \
        --snapshotUri https://example.company.com/snapshot
----

When you do not provide the username and password parameters, Mill will instead look for the `MILL_MAVEN_USERNAME` and
`MILL_MAVEN_PASSWORD` environment variables. Providing the credentials via environment variables is the recommended
approach due to security considerations.

=== Non-Staging Releases (classic Maven uploads)

If the site does not support staging releases as `oss.sonatype.org` and `s01.oss.sonatype.org` do (for
example, a self-hosted OSS nexus site), you can pass in the
`--stagingRelease false` option to simply upload release artifacts to corresponding
maven path under `sonatypeUri` instead of staging path.

[source,console]
----
> mill mill.scalalib.PublishModule/ \
        --publishArtifacts foo.publishArtifacts \
        --sonatypeCreds lihaoyi:$SONATYPE_PASSWORD \
        --sonatypeUri http://example.company.com/release \
        --stagingRelease false
----


== `SonatypeCentralPublishModule` Configurations

This module provides settings and a CLI interface for publishing artifacts to Sonatype Maven Central.
You can configure it through your `build.mill` file or by passing command-line options to it.

=== Argument Reference

==== publishAll

The `publishAll` task can be called from the CLI. If a required value is not provided via the CLI option,
it will fall back to an environment variable (if available) or raise an error if missing.

The `./mill mill.javalib.SonatypeCentralPublishModule/publishAll` takes the following options:

`username`: The username for calling the Sonatype Central publishing api. Defaults to the `SONATYPE_USERNAME` environment variable if unset. If neither the parameter nor the environment variable are set, an error will be thrown. +

`password`: The password for calling the Sonatype Central publishing api. Defaults to the `SONATYPE_PASSWORD` environment variable if unset. If neither the parameter nor the environment variable are set, an error will be thrown. +

`gpgArgs`: Arguments to pass to the gpg package for signing artifacts. Uses the `MILL_PGP_PASSPHRASE` environment variable if set. _Default: `[--passphrase=$MILL_PGP_PASSPHRASE], --no-tty, --pinentry-mode, loopback, --batch, --yes, --armor, --detach-sign`._ +

`publishArtifacts`: The command for generating all publishable artifacts (ex. `__.publishArtifacts`). Required. +

`readTimeout`:  The timeout for receiving a response from Sonatype Central after the initial connection has occurred. _Default: 60000._ +

`awaitTimeout`: The overall timeout for all retries (including exponential backoff) of the bundle upload. _Default: 120 * 1000._ +

`connectTimeout`: The timeout for the initial connection to Sonatype Central if there is no response. _Default: 5000._ +

`shouldRelease`: Whether the bundle should be automatically released when uploaded to Sonatype Central. If `false`, the bundle will still be uploaded, but users will need to manually log in to Sonatype Central and publish the bundle from the portal. _Default: true_ +

`bundleName`: If set, all packages will be uploaded in a single bundle with the given name. If unset, packages will be uploaded separately. Recommended bundle name syntax: groupName-artifactId-versionNumber. As an example, if publishing the `com.lihaoyi` `requests` package, without the bundle name, four different bundles will be uploaded, one for each scala version supported. With a bundle name of `com.lihaoyi-requests-<new_version>`, a single bundle will be uploaded that contains all packages across scala versions. It is recommended to set the bundle name, so that packages can be verified and deployed together. _Default: No bundle name is set and packages will be uploaded separately_

==== Example command

[,console]
----
$ mill -i \
mill.javalib.SonatypeCentralPublishModule/publishAll \
--username myusername \
--password mypassword \
--gpgArgs --passphrase=$MILL_PGP_PASSPHRASE,--no-tty,--pinentry-mode,loopback,--batch,--yes,--armor,--detach-sign \
--publishArtifacts __.publishArtifacts \
--readTimeout  36000 \
--awaitTimeout 36000 \
--connectTimeout 36000 \
--shouldRelease false \
--bundleName com.lihaoyi-requests:1.0.0
----

==== publishSonatypeCentral

The `__.publishSonatypeCentral` command takes the `username` and `password` arguments, documented above.


== Publishing to other repositories

While Sonatype Maven Central is the default publish repository for JVM ecosystem projects,
there are also others that you can use. Mill supports these largely through contrib plugins:

* xref:contrib/codeartifact.adoc[]
* xref:contrib/artifactory.adoc[]
