extends: [mill.kotlinlib.KotlinModule]
kotlinVersion: 1.9.24
mvnDeps:
- org.jetbrains.kotlinx:kotlinx-html:0.11.0

# Add a custom maven repository URL
repositories: ["https://oss.sonatype.org/content/repositories/releases"]

# Set an explicit main class
mainClass: "foo.Foo2Kt"

# Add an additional source folder and resource folder, in addition to the default one
sources: ["./src", "./custom-src"]
resources: ["./resources", "./custom-resources"]

# Configure JVM runtime options and env vars
forkArgs: ["-Dmy.custom.property=my-prop-value"]
forkEnv: { "MY_CUSTOM_ENV": "my-env-value" }