= Building Groovy with Mill
:page-aliases: Groovy_Intro_to_Mill.adoc
:language: Groovy
:language-small: groovy

// START-COPY-AND-PASTE
// Instead of this include
// include::partial$Intro_Header.adoc[]
// We copy the text here, as we currently have no publishing page

This page contains a quick introduction to getting start with using Mill to build
a simple {language} program. It walks through a series of Mill builds of increasing
complexity to show you the key features and usage of the Mill build tool.
The other pages of this section of the docs go into more depth into individual Mill features.
These aren't intended to be read comprehensively top-to-bottom, but
rather looked up when you have a particular interest e.g. in
xref:{language-small}lib/testing.adoc[testing],
xref:javalib/publishing.adoc[publishing], and so on.

The API reference for Mill's {language} toolchain can be found at:

* {mill-doc-url}/api/latest/mill/{language-small}lib.html[mill.{language-small}lib]

If you aren't sure why you would use Mill, see xref:comparisons/why-mill.adoc[] for
a discussion on the motivations of the project. If you are migrating an existing project,
see xref:migrating/migrating.adoc[Migrating to Mill].

// END-COPY-AND-PASTE

NOTE: Mill Groovy support is currently still under active development.
It is expected to continue evolving over time.

== Simple Groovy Module

include::partial$example/groovylib/basic/1-simple.adoc[]

== Maven-Compatible Modules

include::partial$example/groovylib/basic/2-compat-modules.adoc[]

== Testing Groovy Projects
:page-aliases: Testing_Groovy_Projects.adoc


This page will discuss common topics around working with test suites using the Mill build tool

=== Defining Unit Test Suites

include::partial$example/groovylib/testing/1-test-suite.adoc[]

=== Defining Integration Test Suites

include::partial$example/groovylib/testing/2-integration-suite.adoc[]

=== Using Spock

include::partial$example/groovylib/testing/3-spock.adoc[]

=== Using Spock in Java projects with Maven layout

include::partial$example/groovylib/testing/4-spock-for-java.adoc[]

=== Github Actions Test Reports

If you use Github Actions for CI, you can use https://github.com/mikepenz/action-junit-report in
your pipeline to render the generated `test-report.xml` files nicely on Github. See
https://github.com/com-lihaoyi/mill/pull/4218/files for an example integration

