package mill.contrib.checkstyle

import mill.api.PathRef

/**
 * A report generated by applying a transformation.
 *
 * @param transformation  path to a transformation (eg, XSLT)
 * @param report          path to the generated report
 */
case class TransformedReport(transformation: PathRef, report: PathRef)
object TransformedReport {

  import upickle.default._

  implicit val RW: ReadWriter[TransformedReport] = macroRW[TransformedReport]
}
