# action.yml
inputs:
  java-version:
    required: true
    type: string

  shell:
    required: true
    type: string

  prepareargs:
    default: "__"
    type: string

  os:
    type: string

runs:
  using: "composite"
  steps:
    # For normal PR jobs, just checkout the base_ref the PR is against
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}
      if: ${{ !(github.event_name == 'push' && github.repository != 'com-lihaoyi/mill') }}

    # For fork push jobs, first checkout the version being pushed, then look for the
    # merge-base where the current version forks off from the upstream main branch
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }
      if: ${{ github.event_name == 'push' && github.repository != 'com-lihaoyi/mill' }}

    - run: |
        git fetch https://github.com/com-lihaoyi/mill main
        MERGE_BASE=$(git merge-base FETCH_HEAD HEAD)
        # pretty-print the path between the FETCH_HEAD (main), HEAD, and the merge-base
        git log --graph --pretty=format:"%h %d %ar %s %n" --ancestry-path $MERGE_BASE^1..HEAD --ancestry-path $MERGE_BASE^1..FETCH_HEAD

        git checkout $MERGE_BASE
      shell: bash
      if: ${{ github.event_name == 'push' && github.repository != 'com-lihaoyi/mill' }}

    - run: echo temurin:${{ inputs.java-version }} > .mill-jvm-version
      shell: bash

    - run: chmod -R 777 . # normalize permissions before and after upload/download-artifact
      shell: bash

    - run: mkdir out && touch out/mill-selective-execution.json
      shell: bash

    - run: cat .mill-jvm-version
      shell: bash

    - run: ./mill -i -k selective.prepare ${{ inputs.prepareargs }}
      if: ${{ (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'run-all-tests')) || github.repository != 'com-lihaoyi/mill' }}
      shell: ${{ inputs.shell }}

    - uses: actions/upload-artifact@v4.6.0
      with:
        path: out/mill-selective-execution.json
        name: ${{ inputs.os }}-selective-execution-artifact
        include-hidden-files: true

    - uses: actions/checkout@v4