name: 'autofix.ci'
on:
  pull_request:
jobs:
  autofix:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: sbt/setup-sbt@v1

      - run: |
          ./mill __.fix + mill.javalib.palantirformat.PalantirFormatModule/ + mill.scalalib.scalafmt.ScalafmtModule/scalafmt + mill.kotlinlib.ktlint.KtlintModule/

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a