name: Draft CI

permissions: write-all
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.event.action != 'ready_for_review' && github.event.pull_request.draft
    steps:
      - name: Create status
        run: |
          curl --request POST \
          --url ${{ github.event.pull_request.statuses_url }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "pending",
            "context": "Draft CI / run (pull_request_target)",
            "target_url": ${{ format('"{0}/commits/{1}"', github.event.pull_request.head.repo.html_url, github.event.pull_request.head.ref) }},
            "description": "use CI on your repo fork (link on right) until this PR is ready for review"
            }' \
          --fail-with-body
