name: Draft Status

# We run full CI on push builds to main and on all pull requests
#
# Manual builds (workflow_dispatch) to the main branch are also published
#
# To maximize bug-catching changes while keeping CI times reasonable, we run:
# - All tests on Linux/Java17
# - Fewer tests on Linux/Java11 and Windows/Java17
# - Fewest tests on Windows/Java11
permissions: write-all
on:
  pull_request_target:

# cancel older runs of a pull request;

jobs:
  set_status:
    runs-on: ubuntu-latest
    permissions: write-all 
    steps:
      - name: Get PR source repository URL
        run:
          echo "${{ github.event.pull_request.head.repo.clone_url }}"
      - name: Create status
        run: |
          curl --request POST \
          --url ${{ github.event.pull_request.statuses_url }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "${{ github.event.workflow_run.conclusion }}",
            "context": "unit test (kube)",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail-with-body
