= Scala Single-File Scripts

:language: Scala
:language-small: scala
:language-ext: scala

include::partial$Script_Header.adoc[]

== Bundled Libraries

Mill Scala scripts come with a number of bundled libraries for these use cases. These
are largely the same as the xref:fundamentals/bundled-libraries.adoc[libraries available in Mill build files]:

- https://github.com/com-lihaoyi/os-lib[OS-Lib]
- https://github.com/com-lihaoyi/upickle[uPickle]
- https://github.com/com-lihaoyi/requests-scala[Requests-Scala]
- https://github.com/com-lihaoyi/mainargs[MainArgs]
- https://github.com/com-lihaoyi/PPrint[PPrint]


These libraries can make it more convenient to script simple command-line workflows
interacting with files, subprocesses, and HTTP endpoints.
These bundled libraries are only available in single-file scripts for convenience; in
config-based modules or programmatic modules, you would need to add them to `mvnDeps` explicitly.
You can also disable use of these libraries in scripts via `//| includDefaultScriptMvnDeps: false`.
And as we saw earlier, you can include any other libraries you wish using `//| mvnDeps`.



== Packaging Assemblies and Native Binaries

include::partial$example/scalalib/script/2-packaging.adoc[]

== Opening a Script REPL

To open a Scala REPL with your script loaded and available, you can use the following command.
This can be useful to interactively exercise and experiment with the code defined in
your script.

```scala
./mill -i Foo.scala:console
```

== Custom Script Module Classes

include::partial$example/scalalib/script/3-custom-class.adoc[]


== Relative and Absolute Script moduleDeps

include::partial$example/scalalib/script/4-relative-imports.adoc[]


== Programmatic `moduleDeps`

include::partial$example/scalalib/script/5-programmatic-module-deps.adoc[]

== Script Use Cases

include::partial$example/scalalib/script/6-json-api-client.adoc[]
include::partial$example/scalalib/script/7-html-scraper.adoc[]
include::partial$example/scalalib/script/8-web-server.adoc[]
include::partial$example/scalalib/script/9-database.adoc[]
include::partial$example/scalalib/script/10-static-site.adoc[]