= Large Builds and Monorepos
:page-aliases: Structuring_Large_Builds.adoc

include::partial$gtag-config.adoc[]

This section walks through Mill features and techniques used for managing large builds.
While Mill works great for small single-module projects, it is also able to work
effectively with large projects with hundreds of modules. Mill's own build for the
https://github.com/com-lihaoyi/mill[com-lihaoyi/mill] project has ~400 modules, and
other proprietary projects may have many more.

Mill modules are cheap. Having more modules does not significantly impact performance
or resource usage, build files are incrementally re-compiled when modified, and modules are 
lazily loaded and initialized only when needed. So you are encouraged to break up your project 
into modules to manage the layering of your codebase or benefit from parallelism.

== Selective Execution


include::partial$example/depth/large/9-selective-execution.adoc[]

== Multi-file Builds

include::partial$example/depth/large/10-multi-file-builds.adoc[]

== Helper Files

include::partial$example/depth/large/11-helper-files.adoc[]

== Legacy `.sc` extension

include::partial$example/depth/large/12-helper-files-sc.adoc[]


