= Large Builds and Monorepos
:page-aliases: Structuring_Large_Builds.adoc

include::partial$gtag-config.adoc[]

This section walks through Mill features and techniques used for managing large builds.
While Mill works great for small single-module projects, it is also able to work
effectively with large projects with hundreds of modules. Mill's own build for the
https://github.com/com-lihaoyi/mill[com-lihaoyi/mill] project has ~400 modules, and
other proprietary projects may have many more.

Mill modules are cheap. Having more modules does not significantly impact performance
or resource usage, build files are incrementally re-compiled when modified, and modules are 
lazily loaded and initialized only when needed. So you are encouraged to break up your project 
into modules to manage the layering of your codebase or benefit from parallelism.

== Selective Test Execution

Mill allows you to filter the tests and other tasks you execute based on the set
of files that changed via `mill selectivePrepare <selector>` and
`mill selectiveRun <selector>`. This is useful for managing large codebases, where
running the entire test suite in CI is often very slow, so you only want to run the
tests or tasks in `<selector>` that are affected by the changes you are making.

For example, if you want to run all tests related to the code changes in a pull
request branch, you can do that as follows:

```bash
> git checkout main # start from the target branch of the PR

> ./mill selectivePrepare __.test

> git checkout pull-request-branch # go to the pull request branch

> ./mill selectiveRun __.test
```

In the example above, the first call to `selectivePrepare` will store the input tasks
hashes and task code signatures in `out/mill-selective-execution.json` for the `main`
branch, and the second call to `selectiveRun` will compute the same signatures for
your `pull-request-branch`, and only run tests or other tasks that are downstream of
the files that were changed. This helps keep CI and testing times acceptable by skipping
tests that are unrelated to the code change being tested.

== Multi-file Builds

include::partial$example/depth/large/10-multi-file-builds.adoc[]

== Helper Files

include::partial$example/depth/large/11-helper-files.adoc[]

== Legacy `.sc` extension

include::partial$example/depth/large/12-helper-files-sc.adoc[]


